# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'arm_layout.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Arm(QtWidgets.QWidget):
    def setupUi(self, Arm):
        Arm.setObjectName("Arm")
        Arm.resize(308, 475)
        self.arm_joints = QtWidgets.QLabel(Arm)
        self.arm_joints.setGeometry(QtCore.QRect(10, 10, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.arm_joints.setFont(font)
        self.arm_joints.setObjectName("arm_joints")
        self.joint_one = QtWidgets.QLabel(Arm)
        self.joint_one.setGeometry(QtCore.QRect(10, 60, 21, 17))
        self.joint_one.setObjectName("joint_one")
        self.joint_one_value = QtWidgets.QLCDNumber(Arm)
        self.joint_one_value.setGeometry(QtCore.QRect(10, 80, 71, 31))
        self.joint_one_value.setObjectName("joint_one_value")
        self.joint_two_value = QtWidgets.QLCDNumber(Arm)
        self.joint_two_value.setGeometry(QtCore.QRect(120, 80, 71, 31))
        self.joint_two_value.setObjectName("joint_two_value")
        self.joint_two = QtWidgets.QLabel(Arm)
        self.joint_two.setGeometry(QtCore.QRect(120, 60, 21, 17))
        self.joint_two.setObjectName("joint_two")
        self.joint_three_value = QtWidgets.QLCDNumber(Arm)
        self.joint_three_value.setGeometry(QtCore.QRect(230, 80, 71, 31))
        self.joint_three_value.setObjectName("joint_three_value")
        self.joint_three = QtWidgets.QLabel(Arm)
        self.joint_three.setGeometry(QtCore.QRect(230, 60, 21, 17))
        self.joint_three.setObjectName("joint_three")
        self.joint_four_value = QtWidgets.QLCDNumber(Arm)
        self.joint_four_value.setGeometry(QtCore.QRect(10, 150, 71, 31))
        self.joint_four_value.setObjectName("joint_four_value")
        self.joint_five_value = QtWidgets.QLCDNumber(Arm)
        self.joint_five_value.setGeometry(QtCore.QRect(120, 150, 71, 31))
        self.joint_five_value.setObjectName("joint_five_value")
        self.joint_five = QtWidgets.QLabel(Arm)
        self.joint_five.setGeometry(QtCore.QRect(120, 130, 21, 17))
        self.joint_five.setObjectName("joint_five")
        self.joint_four = QtWidgets.QLabel(Arm)
        self.joint_four.setGeometry(QtCore.QRect(10, 130, 21, 17))
        self.joint_four.setObjectName("joint_four")
        self.error_label = QtWidgets.QLabel(Arm)
        self.error_label.setEnabled(True)
        self.error_label.setGeometry(QtCore.QRect(10, 210, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.error_label.setFont(font)
        self.error_label.setAutoFillBackground(False)
        self.error_label.setStyleSheet("QLabel {background:red}\n"
"")
        self.error_label.setObjectName("error_label")
        self.hand_position_label = QtWidgets.QLabel(Arm)
        self.hand_position_label.setGeometry(QtCore.QRect(10, 250, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.hand_position_label.setFont(font)
        self.hand_position_label.setObjectName("hand_position_label")
        self.hand_position_label_2 = QtWidgets.QLabel(Arm)
        self.hand_position_label_2.setGeometry(QtCore.QRect(10, 360, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.hand_position_label_2.setFont(font)
        self.hand_position_label_2.setObjectName("hand_position_label_2")
        self.hand_x = QtWidgets.QLabel(Arm)
        self.hand_x.setGeometry(QtCore.QRect(40, 290, 21, 17))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.hand_x.setFont(font)
        self.hand_x.setObjectName("hand_x")
        self.hand_y = QtWidgets.QLabel(Arm)
        self.hand_y.setGeometry(QtCore.QRect(150, 290, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.hand_y.setFont(font)
        self.hand_y.setObjectName("hand_y")
        self.hand_z = QtWidgets.QLabel(Arm)
        self.hand_z.setGeometry(QtCore.QRect(250, 290, 21, 17))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.hand_z.setFont(font)
        self.hand_z.setObjectName("hand_z")
        self.orientation_z_val = QtWidgets.QLCDNumber(Arm)
        self.orientation_z_val.setGeometry(QtCore.QRect(230, 420, 71, 31))
        self.orientation_z_val.setObjectName("orientation_z_val")
        self.orientation_y_val = QtWidgets.QLCDNumber(Arm)
        self.orientation_y_val.setGeometry(QtCore.QRect(120, 420, 71, 31))
        self.orientation_y_val.setObjectName("orientation_y_val")
        self.orientation_x_val = QtWidgets.QLCDNumber(Arm)
        self.orientation_x_val.setGeometry(QtCore.QRect(10, 420, 71, 31))
        self.orientation_x_val.setObjectName("orientation_x_val")
        self.hand_z_val = QtWidgets.QLCDNumber(Arm)
        self.hand_z_val.setGeometry(QtCore.QRect(230, 310, 71, 31))
        self.hand_z_val.setObjectName("hand_z_val")
        self.hand_y_val = QtWidgets.QLCDNumber(Arm)
        self.hand_y_val.setGeometry(QtCore.QRect(120, 310, 71, 31))
        self.hand_y_val.setObjectName("hand_y_val")
        self.hand_x_val = QtWidgets.QLCDNumber(Arm)
        self.hand_x_val.setGeometry(QtCore.QRect(10, 310, 71, 31))
        self.hand_x_val.setObjectName("hand_x_val")
        self.orientation_y = QtWidgets.QLabel(Arm)
        self.orientation_y.setGeometry(QtCore.QRect(150, 400, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.orientation_y.setFont(font)
        self.orientation_y.setObjectName("orientation_y")
        self.orientation_x = QtWidgets.QLabel(Arm)
        self.orientation_x.setGeometry(QtCore.QRect(40, 400, 21, 17))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.orientation_x.setFont(font)
        self.orientation_x.setObjectName("orientation_x")
        self.orientation_z = QtWidgets.QLabel(Arm)
        self.orientation_z.setGeometry(QtCore.QRect(250, 400, 21, 17))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.orientation_z.setFont(font)
        self.orientation_z.setObjectName("orientation_z")

        self.retranslateUi(Arm)
        QtCore.QMetaObject.connectSlotsByName(Arm)

    def retranslateUi(self, Arm):
        _translate = QtCore.QCoreApplication.translate
        Arm.setWindowTitle(_translate("Arm", "Form"))
        self.arm_joints.setText(_translate("Arm", "Arm Joints"))
        self.joint_one.setText(_translate("Arm", "#1"))
        self.joint_two.setText(_translate("Arm", "#1"))
        self.joint_three.setText(_translate("Arm", "#1"))
        self.joint_five.setText(_translate("Arm", "#1"))
        self.joint_four.setText(_translate("Arm", "#1"))
        self.error_label.setText(_translate("Arm", "Error"))
        self.hand_position_label.setText(_translate("Arm", "Hand Position"))
        self.hand_position_label_2.setText(_translate("Arm", "Orientation"))
        self.hand_x.setText(_translate("Arm", "X:"))
        self.hand_y.setText(_translate("Arm", "Y:"))
        self.hand_z.setText(_translate("Arm", "Z:"))
        self.orientation_y.setText(_translate("Arm", "Y:"))
        self.orientation_x.setText(_translate("Arm", "X:"))
        self.orientation_z.setText(_translate("Arm", "Z:"))
