# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'drive_layout.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DriveTab(QtWidgets.QWidget):
    def setupUi(self, Drive):
        Drive.setObjectName("Drive")
        Drive.resize(515, 615)
        Drive.setAutoFillBackground(True)
        self.right_speed_data = QtWidgets.QLCDNumber(Drive)
        self.right_speed_data.setGeometry(QtCore.QRect(120, 40, 71, 31))
        self.right_speed_data.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.right_speed_data.setObjectName("right_speed_data")
        self.right_speed_label = QtWidgets.QLabel(Drive)
        self.right_speed_label.setGeometry(QtCore.QRect(116, 70, 91, 21))
        self.right_speed_label.setObjectName("right_speed_label")
        self.rear_left_speed_data = QtWidgets.QLCDNumber(Drive)
        self.rear_left_speed_data.setGeometry(QtCore.QRect(20, 100, 71, 31))
        self.rear_left_speed_data.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.rear_left_speed_data.setObjectName("rear_left_speed_data")
        self.left_speed_label = QtWidgets.QLabel(Drive)
        self.left_speed_label.setGeometry(QtCore.QRect(20, 70, 81, 21))
        self.left_speed_label.setObjectName("left_speed_label")
        self.left_speed_data = QtWidgets.QLCDNumber(Drive)
        self.left_speed_data.setGeometry(QtCore.QRect(20, 40, 71, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.left_speed_data.setFont(font)
        self.left_speed_data.setSmallDecimalPoint(False)
        self.left_speed_data.setDigitCount(5)
        self.left_speed_data.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.left_speed_data.setProperty("value", 0.0)
        self.left_speed_data.setProperty("intValue", 0)
        self.left_speed_data.setObjectName("left_speed_data")
        self.rear_right_speed_label = QtWidgets.QLabel(Drive)
        self.rear_right_speed_label.setGeometry(QtCore.QRect(120, 130, 91, 20))
        self.rear_right_speed_label.setObjectName("rear_right_speed_label")
        self.rear_right_speed_data = QtWidgets.QLCDNumber(Drive)
        self.rear_right_speed_data.setGeometry(QtCore.QRect(120, 100, 71, 31))
        self.rear_right_speed_data.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.rear_right_speed_data.setObjectName("rear_right_speed_data")
        self.rear_left_speed_label = QtWidgets.QLabel(Drive)
        self.rear_left_speed_label.setGeometry(QtCore.QRect(20, 120, 81, 41))
        self.rear_left_speed_label.setObjectName("rear_left_speed_label")
        self.wheel_velocity_label = QtWidgets.QLabel(Drive)
        self.wheel_velocity_label.setGeometry(QtCore.QRect(10, 10, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.wheel_velocity_label.setFont(font)
        self.wheel_velocity_label.setScaledContents(True)
        self.wheel_velocity_label.setObjectName("wheel_velocity_label")
        self.twist_label = QtWidgets.QLabel(Drive)
        self.twist_label.setGeometry(QtCore.QRect(20, 180, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.twist_label.setFont(font)
        self.twist_label.setObjectName("twist_label")
        self.twist_linear_velocity = QtWidgets.QLCDNumber(Drive)
        self.twist_linear_velocity.setGeometry(QtCore.QRect(20, 210, 71, 31))
        self.twist_linear_velocity.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.twist_linear_velocity.setObjectName("twist_linear_velocity")
        self.twist_angular_velocity = QtWidgets.QLCDNumber(Drive)
        self.twist_angular_velocity.setGeometry(QtCore.QRect(100, 210, 81, 31))
        self.twist_angular_velocity.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.twist_angular_velocity.setObjectName("twist_angular_velocity")
        self.twist_linear_velocity_label = QtWidgets.QLabel(Drive)
        self.twist_linear_velocity_label.setGeometry(QtCore.QRect(30, 250, 51, 16))
        self.twist_linear_velocity_label.setObjectName("twist_linear_velocity_label")
        self.twist_angular_velocity_label = QtWidgets.QLabel(Drive)
        self.twist_angular_velocity_label.setGeometry(QtCore.QRect(110, 250, 61, 21))
        self.twist_angular_velocity_label.setObjectName("twist_angular_velocity_label")
        self.line = QtWidgets.QFrame(Drive)
        self.line.setGeometry(QtCore.QRect(0, 160, 681, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.line.setFont(font)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Drive)
        self.line_2.setGeometry(QtCore.QRect(0, 270, 681, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.current_robot_location_label = QtWidgets.QLabel(Drive)
        self.current_robot_location_label.setGeometry(QtCore.QRect(20, 300, 231, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.current_robot_location_label.setFont(font)
        self.current_robot_location_label.setObjectName("current_robot_location_label")
        self.line_3 = QtWidgets.QFrame(Drive)
        self.line_3.setGeometry(QtCore.QRect(0, 460, 681, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.robot_location_x = QtWidgets.QLCDNumber(Drive)
        self.robot_location_x.setGeometry(QtCore.QRect(20, 330, 71, 31))
        self.robot_location_x.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.robot_location_x.setObjectName("robot_location_x")
        self.robot_location_y = QtWidgets.QLCDNumber(Drive)
        self.robot_location_y.setGeometry(QtCore.QRect(100, 330, 71, 31))
        self.robot_location_y.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.robot_location_y.setObjectName("robot_location_y")
        self.robot_location_x_label = QtWidgets.QLabel(Drive)
        self.robot_location_x_label.setGeometry(QtCore.QRect(40, 363, 47, 20))
        self.robot_location_x_label.setObjectName("robot_location_x_label")
        self.robot_location_y_label = QtWidgets.QLabel(Drive)
        self.robot_location_y_label.setGeometry(QtCore.QRect(130, 360, 47, 21))
        self.robot_location_y_label.setObjectName("robot_location_y_label")
        self.robot_location_z = QtWidgets.QLCDNumber(Drive)
        self.robot_location_z.setGeometry(QtCore.QRect(180, 330, 71, 31))
        self.robot_location_z.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.robot_location_z.setObjectName("robot_location_z")
        self.robot_location_z_label = QtWidgets.QLabel(Drive)
        self.robot_location_z_label.setGeometry(QtCore.QRect(200, 360, 51, 21))
        self.robot_location_z_label.setObjectName("robot_location_z_label")
        self.robot_location_roll = QtWidgets.QLCDNumber(Drive)
        self.robot_location_roll.setGeometry(QtCore.QRect(20, 390, 71, 31))
        self.robot_location_roll.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.robot_location_roll.setObjectName("robot_location_roll")
        self.robot_location_pitch = QtWidgets.QLCDNumber(Drive)
        self.robot_location_pitch.setGeometry(QtCore.QRect(100, 390, 71, 31))
        self.robot_location_pitch.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.robot_location_pitch.setObjectName("robot_location_pitch")
        self.robot_location_yaw = QtWidgets.QLCDNumber(Drive)
        self.robot_location_yaw.setGeometry(QtCore.QRect(180, 390, 71, 31))
        self.robot_location_yaw.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.robot_location_yaw.setObjectName("robot_location_yaw")
        self.robot_location_roll_label = QtWidgets.QLabel(Drive)
        self.robot_location_roll_label.setGeometry(QtCore.QRect(40, 420, 47, 20))
        self.robot_location_roll_label.setObjectName("robot_location_roll_label")
        self.robot_location_pitch_label = QtWidgets.QLabel(Drive)
        self.robot_location_pitch_label.setGeometry(QtCore.QRect(130, 420, 47, 21))
        self.robot_location_pitch_label.setObjectName("robot_location_pitch_label")
        self.robot_location_yaw_label = QtWidgets.QLabel(Drive)
        self.robot_location_yaw_label.setGeometry(QtCore.QRect(200, 420, 51, 21))
        self.robot_location_yaw_label.setObjectName("robot_location_yaw_label")
        self.error_label = QtWidgets.QTextBrowser(Drive)
        self.error_label.setGeometry(QtCore.QRect(10, 510, 271, 91))
        self.error_label.setObjectName("error_label")
        self.error_message_label = QtWidgets.QLabel(Drive)
        self.error_message_label.setGeometry(QtCore.QRect(20, 470, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.error_message_label.setFont(font)
        self.error_message_label.setObjectName("error_message_label")
        self.AntennaBox = QtWidgets.QLabel(Drive)
        self.AntennaBox.setGeometry(QtCore.QRect(249, 16, 101, 17))
        self.AntennaBox.setObjectName("AntennaBox")
        self.heading_val = QtWidgets.QLineEdit(Drive)
        self.heading_val.setGeometry(QtCore.QRect(326, 99, 41, 25))
        self.heading_val.setObjectName("heading_val")
        self.send_antenna = QtWidgets.QPushButton(Drive)
        self.send_antenna.setGeometry(QtCore.QRect(250, 130, 80, 25))
        self.send_antenna.setObjectName("send_antenna")
        self.LatitudeLabel = QtWidgets.QLabel(Drive)
        self.LatitudeLabel.setGeometry(QtCore.QRect(250, 37, 58, 17))
        self.LatitudeLabel.setObjectName("LatitudeLabel")
        self.longitude_val = QtWidgets.QLineEdit(Drive)
        self.longitude_val.setGeometry(QtCore.QRect(326, 68, 41, 25))
        self.longitude_val.setObjectName("longitude_val")
        self.HeadingLabel = QtWidgets.QLabel(Drive)
        self.HeadingLabel.setGeometry(QtCore.QRect(250, 99, 57, 17))
        self.HeadingLabel.setObjectName("HeadingLabel")
        self.latitude_val = QtWidgets.QLineEdit(Drive)
        self.latitude_val.setGeometry(QtCore.QRect(326, 37, 41, 25))
        self.latitude_val.setObjectName("latitude_val")
        self.LongitudeLabel = QtWidgets.QLabel(Drive)
        self.LongitudeLabel.setGeometry(QtCore.QRect(250, 68, 70, 17))
        self.LongitudeLabel.setObjectName("LongitudeLabel")

        self.retranslateUi(Drive)
        QtCore.QMetaObject.connectSlotsByName(Drive)

    def retranslateUi(self, Drive):
        _translate = QtCore.QCoreApplication.translate
        Drive.setWindowTitle(_translate("Drive", "Form"))
        self.right_speed_label.setText(_translate("Drive", "Front_Right"))
        self.left_speed_label.setText(_translate("Drive", "Front_Left"))
        self.rear_right_speed_label.setText(_translate("Drive", "Rear_Right"))
        self.rear_left_speed_label.setText(_translate("Drive", "Rear_Left"))
        self.wheel_velocity_label.setText(_translate("Drive", "Wheel Velocities (Angular)"))
        self.twist_label.setText(_translate("Drive", "Twist"))
        self.twist_linear_velocity_label.setText(_translate("Drive", "Linear"))
        self.twist_angular_velocity_label.setText(_translate("Drive", "Angular"))
        self.current_robot_location_label.setText(_translate("Drive", "Current Robot Location"))
        self.robot_location_x_label.setText(_translate("Drive", "x"))
        self.robot_location_y_label.setText(_translate("Drive", "y"))
        self.robot_location_z_label.setText(_translate("Drive", "z"))
        self.robot_location_roll_label.setText(_translate("Drive", "roll"))
        self.robot_location_pitch_label.setText(_translate("Drive", "pitch"))
        self.robot_location_yaw_label.setText(_translate("Drive", "yaw"))
        self.error_message_label.setText(_translate("Drive", "Error Message"))
        self.AntennaBox.setText(_translate("Drive", "Antenna Data"))
        self.send_antenna.setText(_translate("Drive", "Send!"))
        self.LatitudeLabel.setText(_translate("Drive", "Latitude"))
        self.HeadingLabel.setText(_translate("Drive", "Heading"))
        self.LongitudeLabel.setText(_translate("Drive", "Longitude"))
