# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_ui_files/power_layout.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(427, 475)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.wheel_left_front_value = QtWidgets.QLCDNumber(Form)
        self.wheel_left_front_value.setObjectName("wheel_left_front_value")
        self.gridLayout_6.addWidget(self.wheel_left_front_value, 0, 1, 1, 1)
        self.wheel_right_back_value = QtWidgets.QLCDNumber(Form)
        self.wheel_right_back_value.setObjectName("wheel_right_back_value")
        self.gridLayout_6.addWidget(self.wheel_right_back_value, 3, 1, 1, 1)
        self.wheel_left_back_value = QtWidgets.QLCDNumber(Form)
        self.wheel_left_back_value.setObjectName("wheel_left_back_value")
        self.gridLayout_6.addWidget(self.wheel_left_back_value, 1, 1, 1, 1)
        self.science_motors_value = QtWidgets.QLCDNumber(Form)
        self.science_motors_value.setObjectName("science_motors_value")
        self.gridLayout_6.addWidget(self.science_motors_value, 2, 3, 1, 1)
        self.wheel_right_front_value = QtWidgets.QLCDNumber(Form)
        self.wheel_right_front_value.setObjectName("wheel_right_front_value")
        self.gridLayout_6.addWidget(self.wheel_right_front_value, 2, 1, 1, 1)
        self.science_steppers_value = QtWidgets.QLCDNumber(Form)
        self.science_steppers_value.setObjectName("science_steppers_value")
        self.gridLayout_6.addWidget(self.science_steppers_value, 3, 3, 1, 1)
        self.wheel_left_back = QtWidgets.QLabel(Form)
        self.wheel_left_back.setObjectName("wheel_left_back")
        self.gridLayout_6.addWidget(self.wheel_left_back, 1, 0, 1, 1)
        self.wheel_left_front = QtWidgets.QLabel(Form)
        self.wheel_left_front.setObjectName("wheel_left_front")
        self.gridLayout_6.addWidget(self.wheel_left_front, 0, 0, 1, 1)
        self.wheel_right_back = QtWidgets.QLabel(Form)
        self.wheel_right_back.setObjectName("wheel_right_back")
        self.gridLayout_6.addWidget(self.wheel_right_back, 3, 0, 1, 1)
        self.wheel_right_front = QtWidgets.QLabel(Form)
        self.wheel_right_front.setObjectName("wheel_right_front")
        self.gridLayout_6.addWidget(self.wheel_right_front, 2, 0, 1, 1)
        self.lower_arm_value = QtWidgets.QLCDNumber(Form)
        self.lower_arm_value.setObjectName("lower_arm_value")
        self.gridLayout_6.addWidget(self.lower_arm_value, 0, 3, 1, 1)
        self.upper_arm_value = QtWidgets.QLCDNumber(Form)
        self.upper_arm_value.setObjectName("upper_arm_value")
        self.gridLayout_6.addWidget(self.upper_arm_value, 1, 3, 1, 1)
        self.lower_arm = QtWidgets.QLabel(Form)
        self.lower_arm.setObjectName("lower_arm")
        self.gridLayout_6.addWidget(self.lower_arm, 0, 2, 1, 1)
        self.upper_arm = QtWidgets.QLabel(Form)
        self.upper_arm.setObjectName("upper_arm")
        self.gridLayout_6.addWidget(self.upper_arm, 1, 2, 1, 1)
        self.science_motors = QtWidgets.QLabel(Form)
        self.science_motors.setObjectName("science_motors")
        self.gridLayout_6.addWidget(self.science_motors, 2, 2, 1, 1)
        self.science_steppers = QtWidgets.QLabel(Form)
        self.science_steppers.setObjectName("science_steppers")
        self.gridLayout_6.addWidget(self.science_steppers, 3, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_6, 1, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.battery1_label = QtWidgets.QLabel(Form)
        self.battery1_label.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.battery1_label.setFont(font)
        self.battery1_label.setObjectName("battery1_label")
        self.verticalLayout_2.addWidget(self.battery1_label)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.current_label_1 = QtWidgets.QLabel(Form)
        self.current_label_1.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.current_label_1.setFont(font)
        self.current_label_1.setObjectName("current_label_1")
        self.horizontalLayout_6.addWidget(self.current_label_1)
        self.current_value_1 = QtWidgets.QLCDNumber(Form)
        self.current_value_1.setObjectName("current_value_1")
        self.horizontalLayout_6.addWidget(self.current_value_1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.verticalLayout_2.addLayout(self.verticalLayout_4)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.battery2_label_2 = QtWidgets.QLabel(Form)
        self.battery2_label_2.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.battery2_label_2.setFont(font)
        self.battery2_label_2.setObjectName("battery2_label_2")
        self.verticalLayout_3.addWidget(self.battery2_label_2)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.current_label_2 = QtWidgets.QLabel(Form)
        self.current_label_2.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.current_label_2.setFont(font)
        self.current_label_2.setObjectName("current_label_2")
        self.horizontalLayout_9.addWidget(self.current_label_2)
        self.current_value_2 = QtWidgets.QLCDNumber(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.current_value_2.setFont(font)
        self.current_value_2.setObjectName("current_value_2")
        self.horizontalLayout_9.addWidget(self.current_value_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.verticalLayout_3.addLayout(self.verticalLayout_5)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.system_enabled_label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.system_enabled_label.setFont(font)
        self.system_enabled_label.setObjectName("system_enabled_label")
        self.horizontalLayout_3.addWidget(self.system_enabled_label)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.drive_enabled = QtWidgets.QCheckBox(Form)
        self.drive_enabled.setObjectName("drive_enabled")
        self.gridLayout_5.addWidget(self.drive_enabled, 0, 0, 1, 1)
        self.lower_arm_enabled = QtWidgets.QCheckBox(Form)
        self.lower_arm_enabled.setObjectName("lower_arm_enabled")
        self.gridLayout_5.addWidget(self.lower_arm_enabled, 2, 0, 1, 1)
        self.science_enabled = QtWidgets.QCheckBox(Form)
        self.science_enabled.setObjectName("science_enabled")
        self.gridLayout_5.addWidget(self.science_enabled, 0, 1, 1, 1)
        self.upper_arm_enable = QtWidgets.QCheckBox(Form)
        self.upper_arm_enable.setObjectName("upper_arm_enable")
        self.gridLayout_5.addWidget(self.upper_arm_enable, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_5)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.wheel_left_back.setText(_translate("Form", "Back Left Wheel"))
        self.wheel_left_front.setText(_translate("Form", "Front Left Wheel"))
        self.wheel_right_back.setText(_translate("Form", "Back Right Wheel"))
        self.wheel_right_front.setText(_translate("Form", "Front Right Wheel"))
        self.lower_arm.setText(_translate("Form", "Lower Arm"))
        self.upper_arm.setText(_translate("Form", "Upper Arm"))
        self.science_motors.setText(_translate("Form", "Science Motors"))
        self.science_steppers.setText(_translate("Form", "Science Steppers"))
        self.battery1_label.setText(_translate("Form", "Battery 1"))
        self.current_label_1.setText(_translate("Form", "Current"))
        self.battery2_label_2.setText(_translate("Form", "Battery 2"))
        self.current_label_2.setText(_translate("Form", "Current"))
        self.system_enabled_label.setText(_translate("Form", "System Enabled"))
        self.drive_enabled.setText(_translate("Form", "Drive"))
        self.lower_arm_enabled.setText(_translate("Form", "Lower Arm"))
        self.science_enabled.setText(_translate("Form", "Science"))
        self.upper_arm_enable.setText(_translate("Form", "Upper Arm"))
