# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'power_layout.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Power(QtWidgets.QWidget):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(492, 475)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.battery_lifetime_label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.battery_lifetime_label.setFont(font)
        self.battery_lifetime_label.setObjectName("battery_lifetime_label")
        self.horizontalLayout_2.addWidget(self.battery_lifetime_label)
        self.line_6 = QtWidgets.QFrame(Form)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout_2.addWidget(self.line_6)
        self.battery_lifetime_value = QtWidgets.QLCDNumber(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.battery_lifetime_value.setFont(font)
        self.battery_lifetime_value.setObjectName("battery_lifetime_value")
        self.horizontalLayout_2.addWidget(self.battery_lifetime_value)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line_3 = QtWidgets.QFrame(Form)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.system_enabled_label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.system_enabled_label.setFont(font)
        self.system_enabled_label.setObjectName("system_enabled_label")
        self.horizontalLayout_3.addWidget(self.system_enabled_label)
        self.line_7 = QtWidgets.QFrame(Form)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.horizontalLayout_3.addWidget(self.line_7)
        self.system_enabled_bool = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.system_enabled_bool.setFont(font)
        self.system_enabled_bool.setObjectName("system_enabled_bool")
        self.horizontalLayout_3.addWidget(self.system_enabled_bool)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.line_4 = QtWidgets.QFrame(Form)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout.addWidget(self.line_4)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.kill_switch_label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.kill_switch_label.setFont(font)
        self.kill_switch_label.setObjectName("kill_switch_label")
        self.horizontalLayout_4.addWidget(self.kill_switch_label)
        self.line_8 = QtWidgets.QFrame(Form)
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.horizontalLayout_4.addWidget(self.line_8)
        self.kill_switch_bool = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.kill_switch_bool.setFont(font)
        self.kill_switch_bool.setObjectName("kill_switch_bool")
        self.horizontalLayout_4.addWidget(self.kill_switch_bool)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.line_5 = QtWidgets.QFrame(Form)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout.addWidget(self.line_5)
        self.kill_power_button = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.kill_power_button.setFont(font)
        self.kill_power_button.setObjectName("kill_power_button")
        self.verticalLayout.addWidget(self.kill_power_button)
        self.gridLayout.addLayout(self.verticalLayout, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.battery1_label = QtWidgets.QLabel(Form)
        self.battery1_label.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.battery1_label.setFont(font)
        self.battery1_label.setObjectName("battery1_label")
        self.verticalLayout_2.addWidget(self.battery1_label)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.voltage_label_1 = QtWidgets.QLabel(Form)
        self.voltage_label_1.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.voltage_label_1.setFont(font)
        self.voltage_label_1.setObjectName("voltage_label_1")
        self.horizontalLayout_5.addWidget(self.voltage_label_1)
        self.voltage_value_1 = QtWidgets.QLCDNumber(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.voltage_value_1.setFont(font)
        self.voltage_value_1.setObjectName("voltage_value_1")
        self.horizontalLayout_5.addWidget(self.voltage_value_1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.current_label_1 = QtWidgets.QLabel(Form)
        self.current_label_1.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.current_label_1.setFont(font)
        self.current_label_1.setObjectName("current_label_1")
        self.horizontalLayout_6.addWidget(self.current_label_1)
        self.current_value_1 = QtWidgets.QLCDNumber(Form)
        self.current_value_1.setObjectName("current_value_1")
        self.horizontalLayout_6.addWidget(self.current_value_1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.power_label_1 = QtWidgets.QLabel(Form)
        self.power_label_1.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.power_label_1.setFont(font)
        self.power_label_1.setObjectName("power_label_1")
        self.horizontalLayout_7.addWidget(self.power_label_1)
        self.power_value_1 = QtWidgets.QLCDNumber(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.power_value_1.setFont(font)
        self.power_value_1.setObjectName("power_value_1")
        self.horizontalLayout_7.addWidget(self.power_value_1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.verticalLayout_2.addLayout(self.verticalLayout_4)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.battery2_label_2 = QtWidgets.QLabel(Form)
        self.battery2_label_2.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.battery2_label_2.setFont(font)
        self.battery2_label_2.setObjectName("battery2_label_2")
        self.verticalLayout_3.addWidget(self.battery2_label_2)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.voltage_label_2 = QtWidgets.QLabel(Form)
        self.voltage_label_2.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.voltage_label_2.setFont(font)
        self.voltage_label_2.setObjectName("voltage_label_2")
        self.horizontalLayout_8.addWidget(self.voltage_label_2)
        self.voltage_value_2 = QtWidgets.QLCDNumber(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.voltage_value_2.setFont(font)
        self.voltage_value_2.setObjectName("voltage_value_2")
        self.horizontalLayout_8.addWidget(self.voltage_value_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.current_label_2 = QtWidgets.QLabel(Form)
        self.current_label_2.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.current_label_2.setFont(font)
        self.current_label_2.setObjectName("current_label_2")
        self.horizontalLayout_9.addWidget(self.current_label_2)
        self.current_value_2 = QtWidgets.QLCDNumber(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.current_value_2.setFont(font)
        self.current_value_2.setObjectName("current_value_2")
        self.horizontalLayout_9.addWidget(self.current_value_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.power_label_2 = QtWidgets.QLabel(Form)
        self.power_label_2.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.power_label_2.setFont(font)
        self.power_label_2.setObjectName("power_label_2")
        self.horizontalLayout_10.addWidget(self.power_label_2)
        self.power_value_2 = QtWidgets.QLCDNumber(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.power_value_2.setFont(font)
        self.power_value_2.setObjectName("power_value_2")
        self.horizontalLayout_10.addWidget(self.power_value_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.verticalLayout_3.addLayout(self.verticalLayout_5)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.battery_lifetime_label.setText(_translate("Form", "Battery Lifetime"))
        self.system_enabled_label.setText(_translate("Form", "System Enabled"))
        self.system_enabled_bool.setText(_translate("Form", "bool"))
        self.kill_switch_label.setText(_translate("Form", "Kill Switch"))
        self.kill_switch_bool.setText(_translate("Form", "bool"))
        self.kill_power_button.setText(_translate("Form", "Kill Power"))
        self.battery1_label.setText(_translate("Form", "Battery 1"))
        self.voltage_label_1.setText(_translate("Form", "Voltage"))
        self.current_label_1.setText(_translate("Form", "Current"))
        self.power_label_1.setText(_translate("Form", "Power"))
        self.battery2_label_2.setText(_translate("Form", "Battery 2"))
        self.voltage_label_2.setText(_translate("Form", "Voltage"))
        self.current_label_2.setText(_translate("Form", "Current"))
        self.power_label_2.setText(_translate("Form", "Power"))
