# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'science_tab_layout.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import buttons_rc

class Ui_Science(QtWidgets.QWidget):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 747)
        font = QtGui.QFont()
        font.setPointSize(10)
        Form.setFont(font)
        self.gridLayout_10 = QtWidgets.QGridLayout(Form)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.Display = QtWidgets.QTabWidget(Form)
        self.Display.setTabPosition(QtWidgets.QTabWidget.West)
        self.Display.setObjectName("Display")
        self.Control = QtWidgets.QWidget()
        self.Control.setObjectName("Control")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.Control)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.scrollArea = QtWidgets.QScrollArea(self.Control)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -56, 418, 761))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.line_4 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_3.addWidget(self.line_4, 15, 0, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_3.addWidget(self.line_6, 5, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.line = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 4, 0, 1, 1)
        self.line_10 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.line_10.setFont(font)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.gridLayout.addWidget(self.line_10, 1, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.stepper1Pos_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepper1Pos_label.sizePolicy().hasHeightForWidth())
        self.stepper1Pos_label.setSizePolicy(sizePolicy)
        self.stepper1Pos_label.setMaximumSize(QtCore.QSize(16777215, 35))
        self.stepper1Pos_label.setObjectName("stepper1Pos_label")
        self.gridLayout_2.addWidget(self.stepper1Pos_label, 1, 0, 2, 1)
        self.stepper1Pos_value = QtWidgets.QLCDNumber(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepper1Pos_value.sizePolicy().hasHeightForWidth())
        self.stepper1Pos_value.setSizePolicy(sizePolicy)
        self.stepper1Pos_value.setMaximumSize(QtCore.QSize(16777215, 50))
        self.stepper1Pos_value.setObjectName("stepper1Pos_value")
        self.gridLayout_2.addWidget(self.stepper1Pos_value, 1, 2, 1, 1)
        self.stepper1Pos_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepper1Pos_doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.stepper1Pos_doubleSpinBox.setSizePolicy(sizePolicy)
        self.stepper1Pos_doubleSpinBox.setObjectName("stepper1Pos_doubleSpinBox")
        self.gridLayout_2.addWidget(self.stepper1Pos_doubleSpinBox, 2, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 3, 0, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout.addWidget(self.line_5, 2, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.gridLayout_23 = QtWidgets.QGridLayout()
        self.gridLayout_23.setObjectName("gridLayout_23")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_23.addItem(spacerItem1, 3, 1, 1, 1)
        self.stepper2Fault_boolLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepper2Fault_boolLabel.sizePolicy().hasHeightForWidth())
        self.stepper2Fault_boolLabel.setSizePolicy(sizePolicy)
        self.stepper2Fault_boolLabel.setMaximumSize(QtCore.QSize(16777215, 50))
        self.stepper2Fault_boolLabel.setObjectName("stepper2Fault_boolLabel")
        self.gridLayout_23.addWidget(self.stepper2Fault_boolLabel, 7, 2, 1, 1)
        self.stepper2Speed_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepper2Speed_label.sizePolicy().hasHeightForWidth())
        self.stepper2Speed_label.setSizePolicy(sizePolicy)
        self.stepper2Speed_label.setMaximumSize(QtCore.QSize(16777215, 35))
        self.stepper2Speed_label.setObjectName("stepper2Speed_label")
        self.gridLayout_23.addWidget(self.stepper2Speed_label, 3, 0, 1, 1)
        self.stepper2Fault_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepper2Fault_label.sizePolicy().hasHeightForWidth())
        self.stepper2Fault_label.setSizePolicy(sizePolicy)
        self.stepper2Fault_label.setMaximumSize(QtCore.QSize(16777215, 50))
        self.stepper2Fault_label.setObjectName("stepper2Fault_label")
        self.gridLayout_23.addWidget(self.stepper2Fault_label, 7, 0, 1, 1)
        self.stepper2Speed_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepper2Speed_doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.stepper2Speed_doubleSpinBox.setSizePolicy(sizePolicy)
        self.stepper2Speed_doubleSpinBox.setObjectName("stepper2Speed_doubleSpinBox")
        self.gridLayout_23.addWidget(self.stepper2Speed_doubleSpinBox, 3, 2, 1, 1)
        self.stepper2ControlMode_spinBox = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepper2ControlMode_spinBox.sizePolicy().hasHeightForWidth())
        self.stepper2ControlMode_spinBox.setSizePolicy(sizePolicy)
        self.stepper2ControlMode_spinBox.setObjectName("stepper2ControlMode_spinBox")
        self.gridLayout_23.addWidget(self.stepper2ControlMode_spinBox, 5, 2, 1, 1)
        self.stepper2ControlMode_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepper2ControlMode_label.sizePolicy().hasHeightForWidth())
        self.stepper2ControlMode_label.setSizePolicy(sizePolicy)
        self.stepper2ControlMode_label.setMaximumSize(QtCore.QSize(16777215, 35))
        self.stepper2ControlMode_label.setObjectName("stepper2ControlMode_label")
        self.gridLayout_23.addWidget(self.stepper2ControlMode_label, 5, 0, 1, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.stepper2Pos_value = QtWidgets.QLCDNumber(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepper2Pos_value.sizePolicy().hasHeightForWidth())
        self.stepper2Pos_value.setSizePolicy(sizePolicy)
        self.stepper2Pos_value.setMaximumSize(QtCore.QSize(16777215, 50))
        self.stepper2Pos_value.setObjectName("stepper2Pos_value")
        self.gridLayout_6.addWidget(self.stepper2Pos_value, 1, 2, 1, 1)
        self.stepper2Pos_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepper2Pos_doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.stepper2Pos_doubleSpinBox.setSizePolicy(sizePolicy)
        self.stepper2Pos_doubleSpinBox.setObjectName("stepper2Pos_doubleSpinBox")
        self.gridLayout_6.addWidget(self.stepper2Pos_doubleSpinBox, 2, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem2, 1, 1, 1, 1)
        self.stepper2Pos_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepper2Pos_label.sizePolicy().hasHeightForWidth())
        self.stepper2Pos_label.setSizePolicy(sizePolicy)
        self.stepper2Pos_label.setMaximumSize(QtCore.QSize(16777215, 35))
        self.stepper2Pos_label.setObjectName("stepper2Pos_label")
        self.gridLayout_6.addWidget(self.stepper2Pos_label, 1, 0, 2, 1)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setObjectName("label_2")
        self.gridLayout_6.addWidget(self.label_2, 0, 1, 1, 1)
        self.gridLayout_23.addLayout(self.gridLayout_6, 1, 0, 1, 3)
        self.line_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_23.addWidget(self.line_3, 2, 0, 1, 3)
        self.gridLayout_3.addLayout(self.gridLayout_23, 6, 0, 1, 1)
        self.gridLayout_22 = QtWidgets.QGridLayout()
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.stepper1Fault_boolLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepper1Fault_boolLabel.sizePolicy().hasHeightForWidth())
        self.stepper1Fault_boolLabel.setSizePolicy(sizePolicy)
        self.stepper1Fault_boolLabel.setMaximumSize(QtCore.QSize(16777215, 50))
        self.stepper1Fault_boolLabel.setObjectName("stepper1Fault_boolLabel")
        self.gridLayout_22.addWidget(self.stepper1Fault_boolLabel, 5, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_22.addItem(spacerItem3, 0, 1, 1, 1)
        self.stepper1Speed_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepper1Speed_doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.stepper1Speed_doubleSpinBox.setSizePolicy(sizePolicy)
        self.stepper1Speed_doubleSpinBox.setObjectName("stepper1Speed_doubleSpinBox")
        self.gridLayout_22.addWidget(self.stepper1Speed_doubleSpinBox, 0, 2, 1, 1)
        self.stepper1Fault_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepper1Fault_label.sizePolicy().hasHeightForWidth())
        self.stepper1Fault_label.setSizePolicy(sizePolicy)
        self.stepper1Fault_label.setMaximumSize(QtCore.QSize(16777215, 50))
        self.stepper1Fault_label.setObjectName("stepper1Fault_label")
        self.gridLayout_22.addWidget(self.stepper1Fault_label, 5, 0, 1, 1)
        self.stepper1ControlMode_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepper1ControlMode_label.sizePolicy().hasHeightForWidth())
        self.stepper1ControlMode_label.setSizePolicy(sizePolicy)
        self.stepper1ControlMode_label.setMaximumSize(QtCore.QSize(16777215, 35))
        self.stepper1ControlMode_label.setObjectName("stepper1ControlMode_label")
        self.gridLayout_22.addWidget(self.stepper1ControlMode_label, 2, 0, 1, 1)
        self.stepper1ControlMode_spinBox = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepper1ControlMode_spinBox.sizePolicy().hasHeightForWidth())
        self.stepper1ControlMode_spinBox.setSizePolicy(sizePolicy)
        self.stepper1ControlMode_spinBox.setObjectName("stepper1ControlMode_spinBox")
        self.gridLayout_22.addWidget(self.stepper1ControlMode_spinBox, 2, 2, 1, 1)
        self.stepper1Speed_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepper1Speed_label.sizePolicy().hasHeightForWidth())
        self.stepper1Speed_label.setSizePolicy(sizePolicy)
        self.stepper1Speed_label.setMaximumSize(QtCore.QSize(16777215, 35))
        self.stepper1Speed_label.setObjectName("stepper1Speed_label")
        self.gridLayout_22.addWidget(self.stepper1Speed_label, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_22, 2, 0, 1, 1)
        self.io_shutdown_button = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.io_shutdown_button.setFont(font)
        self.io_shutdown_button.setObjectName("io_shutdown_button")
        self.gridLayout_3.addWidget(self.io_shutdown_button, 0, 0, 1, 1)
        self.line_9 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.gridLayout_3.addWidget(self.line_9, 4, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_3.addWidget(self.line_2, 8, 0, 1, 1)
        self.line_11 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.gridLayout_3.addWidget(self.line_11, 19, 0, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.contMotorSpeed_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.contMotorSpeed_label.sizePolicy().hasHeightForWidth())
        self.contMotorSpeed_label.setSizePolicy(sizePolicy)
        self.contMotorSpeed_label.setObjectName("contMotorSpeed_label")
        self.horizontalLayout_11.addWidget(self.contMotorSpeed_label)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem4)
        self.contMotorSpeed_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.contMotorSpeed_doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.contMotorSpeed_doubleSpinBox.setSizePolicy(sizePolicy)
        self.contMotorSpeed_doubleSpinBox.setObjectName("contMotorSpeed_doubleSpinBox")
        self.horizontalLayout_11.addWidget(self.contMotorSpeed_doubleSpinBox)
        self.gridLayout_3.addLayout(self.horizontalLayout_11, 17, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.laserState_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.laserState_label.sizePolicy().hasHeightForWidth())
        self.laserState_label.setSizePolicy(sizePolicy)
        self.laserState_label.setMinimumSize(QtCore.QSize(0, 30))
        self.laserState_label.setMaximumSize(QtCore.QSize(16777215, 75))
        self.laserState_label.setObjectName("laserState_label")
        self.horizontalLayout_5.addWidget(self.laserState_label)
        self.line_7 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.horizontalLayout_5.addWidget(self.line_7)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.laserState_toggle = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.laserState_toggle.sizePolicy().hasHeightForWidth())
        self.laserState_toggle.setSizePolicy(sizePolicy)
        self.laserState_toggle.setMinimumSize(QtCore.QSize(60, 30))
        self.laserState_toggle.setStyleSheet("QPushButton{\n"
"    border-image: url(:/buttons/off.png);\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    border-image: url(:/buttons/on.png);\n"
"}")
        self.laserState_toggle.setText("")
        self.laserState_toggle.setCheckable(True)
        self.laserState_toggle.setObjectName("laserState_toggle")
        self.horizontalLayout_5.addWidget(self.laserState_toggle)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 9, 0, 1, 1)
        self.send_button = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.send_button.setFont(font)
        self.send_button.setObjectName("send_button")
        self.gridLayout_3.addWidget(self.send_button, 20, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.ledState_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ledState_label.sizePolicy().hasHeightForWidth())
        self.ledState_label.setSizePolicy(sizePolicy)
        self.ledState_label.setMinimumSize(QtCore.QSize(0, 30))
        self.ledState_label.setMaximumSize(QtCore.QSize(16777215, 75))
        self.ledState_label.setObjectName("ledState_label")
        self.horizontalLayout_6.addWidget(self.ledState_label)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.ledState_toggle = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ledState_toggle.sizePolicy().hasHeightForWidth())
        self.ledState_toggle.setSizePolicy(sizePolicy)
        self.ledState_toggle.setMinimumSize(QtCore.QSize(60, 30))
        self.ledState_toggle.setStyleSheet("QPushButton{\n"
"    border-image: url(:/buttons/off.png);\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    border-image: url(:/buttons/on.png);\n"
"}")
        self.ledState_toggle.setText("")
        self.ledState_toggle.setCheckable(True)
        self.ledState_toggle.setObjectName("ledState_toggle")
        self.horizontalLayout_6.addWidget(self.ledState_toggle)
        self.gridLayout_3.addLayout(self.horizontalLayout_6, 13, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.ccdSensorSnap_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ccdSensorSnap_label.sizePolicy().hasHeightForWidth())
        self.ccdSensorSnap_label.setSizePolicy(sizePolicy)
        self.ccdSensorSnap_label.setMinimumSize(QtCore.QSize(0, 30))
        self.ccdSensorSnap_label.setMaximumSize(QtCore.QSize(16777215, 75))
        self.ccdSensorSnap_label.setObjectName("ccdSensorSnap_label")
        self.horizontalLayout_10.addWidget(self.ccdSensorSnap_label)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem7)
        self.peltierState_toggle_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.peltierState_toggle_2.sizePolicy().hasHeightForWidth())
        self.peltierState_toggle_2.setSizePolicy(sizePolicy)
        self.peltierState_toggle_2.setMinimumSize(QtCore.QSize(60, 30))
        self.peltierState_toggle_2.setStyleSheet("QPushButton{\n"
"    border-image: url(:/buttons/off.png);\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    border-image: url(:/buttons/on.png);\n"
"}")
        self.peltierState_toggle_2.setText("")
        self.peltierState_toggle_2.setCheckable(True)
        self.peltierState_toggle_2.setObjectName("peltierState_toggle_2")
        self.horizontalLayout_10.addWidget(self.peltierState_toggle_2)
        self.gridLayout_3.addLayout(self.horizontalLayout_10, 14, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.coolerState_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.coolerState_label.sizePolicy().hasHeightForWidth())
        self.coolerState_label.setSizePolicy(sizePolicy)
        self.coolerState_label.setMinimumSize(QtCore.QSize(0, 30))
        self.coolerState_label.setMaximumSize(QtCore.QSize(16777215, 75))
        self.coolerState_label.setObjectName("coolerState_label")
        self.horizontalLayout_8.addWidget(self.coolerState_label)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem8)
        self.coolerState_bool = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.coolerState_bool.sizePolicy().hasHeightForWidth())
        self.coolerState_bool.setSizePolicy(sizePolicy)
        self.coolerState_bool.setMinimumSize(QtCore.QSize(0, 30))
        self.coolerState_bool.setMaximumSize(QtCore.QSize(16777215, 75))
        self.coolerState_bool.setObjectName("coolerState_bool")
        self.horizontalLayout_8.addWidget(self.coolerState_bool)
        self.gridLayout_3.addLayout(self.horizontalLayout_8, 16, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.gripperState_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gripperState_label.sizePolicy().hasHeightForWidth())
        self.gripperState_label.setSizePolicy(sizePolicy)
        self.gripperState_label.setMinimumSize(QtCore.QSize(0, 30))
        self.gripperState_label.setMaximumSize(QtCore.QSize(16777215, 75))
        self.gripperState_label.setObjectName("gripperState_label")
        self.horizontalLayout_7.addWidget(self.gripperState_label)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem9)
        self.gripperState_toggle = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gripperState_toggle.sizePolicy().hasHeightForWidth())
        self.gripperState_toggle.setSizePolicy(sizePolicy)
        self.gripperState_toggle.setMinimumSize(QtCore.QSize(60, 30))
        self.gripperState_toggle.setStyleSheet("QPushButton{\n"
"    border-image: url(:/buttons/off.png);\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    border-image: url(:/buttons/on.png);\n"
"}")
        self.gripperState_toggle.setText("")
        self.gripperState_toggle.setCheckable(True)
        self.gripperState_toggle.setObjectName("gripperState_toggle")
        self.horizontalLayout_7.addWidget(self.gripperState_toggle)
        self.gridLayout_3.addLayout(self.horizontalLayout_7, 11, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.peltierState_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.peltierState_label.sizePolicy().hasHeightForWidth())
        self.peltierState_label.setSizePolicy(sizePolicy)
        self.peltierState_label.setMinimumSize(QtCore.QSize(0, 30))
        self.peltierState_label.setMaximumSize(QtCore.QSize(16777215, 75))
        self.peltierState_label.setObjectName("peltierState_label")
        self.horizontalLayout_9.addWidget(self.peltierState_label)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem10)
        self.peltierState_toggle = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.peltierState_toggle.sizePolicy().hasHeightForWidth())
        self.peltierState_toggle.setSizePolicy(sizePolicy)
        self.peltierState_toggle.setMinimumSize(QtCore.QSize(60, 30))
        self.peltierState_toggle.setStyleSheet("QPushButton{\n"
"    border-image: url(:/buttons/off.png);\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    border-image: url(:/buttons/on.png);\n"
"}")
        self.peltierState_toggle.setText("")
        self.peltierState_toggle.setCheckable(True)
        self.peltierState_toggle.setObjectName("peltierState_toggle")
        self.horizontalLayout_9.addWidget(self.peltierState_toggle)
        self.gridLayout_3.addLayout(self.horizontalLayout_9, 10, 0, 1, 1)
        self.line_8 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout_3.addWidget(self.line_8, 18, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_4.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.Display.addTab(self.Control, "")
        self.Camera = QtWidgets.QWidget()
        self.Camera.setObjectName("Camera")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.Camera)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.Camera)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 432, 705))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.microcamera_image_label = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.microcamera_image_label.setFont(font)
        self.microcamera_image_label.setObjectName("microcamera_image_label")
        self.verticalLayout_3.addWidget(self.microcamera_image_label)
        self.microcamera_image_graphicsView = QtWidgets.QGraphicsView(self.scrollAreaWidgetContents_2)
        self.microcamera_image_graphicsView.setObjectName("microcamera_image_graphicsView")
        self.verticalLayout_3.addWidget(self.microcamera_image_graphicsView)
        self.gridLayout_8.addLayout(self.verticalLayout_3, 1, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ccd_image_label = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ccd_image_label.setFont(font)
        self.ccd_image_label.setObjectName("ccd_image_label")
        self.verticalLayout_2.addWidget(self.ccd_image_label)
        self.ccd_image_graphicsView = QtWidgets.QGraphicsView(self.scrollAreaWidgetContents_2)
        self.ccd_image_graphicsView.setObjectName("ccd_image_graphicsView")
        self.verticalLayout_2.addWidget(self.ccd_image_graphicsView)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.gridLayout_8.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.ml_row1 = QtWidgets.QVBoxLayout()
        self.ml_row1.setObjectName("ml_row1")
        self.ml_classifier_label = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ml_classifier_label.setFont(font)
        self.ml_classifier_label.setObjectName("ml_classifier_label")
        self.ml_row1.addWidget(self.ml_classifier_label)
        self.line_29 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_29.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_29.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_29.setObjectName("line_29")
        self.ml_row1.addWidget(self.line_29)
        self.ml_classifier_layout = QtWidgets.QFormLayout()
        self.ml_classifier_layout.setObjectName("ml_classifier_layout")
        self.ml_classifier_class1_label1 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.ml_classifier_class1_label1.setObjectName("ml_classifier_class1_label1")
        self.ml_classifier_layout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.ml_classifier_class1_label1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ml_classifier_class1_label2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.ml_classifier_class1_label2.setObjectName("ml_classifier_class1_label2")
        self.horizontalLayout_2.addWidget(self.ml_classifier_class1_label2)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem11)
        self.ml_classifier_class1_display = QtWidgets.QLCDNumber(self.scrollAreaWidgetContents_2)
        self.ml_classifier_class1_display.setObjectName("ml_classifier_class1_display")
        self.horizontalLayout_2.addWidget(self.ml_classifier_class1_display)
        self.ml_classifier_layout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.ml_classifier_class2_label1 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.ml_classifier_class2_label1.setObjectName("ml_classifier_class2_label1")
        self.ml_classifier_layout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.ml_classifier_class2_label1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ml_classifier_class2_label2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.ml_classifier_class2_label2.setObjectName("ml_classifier_class2_label2")
        self.horizontalLayout.addWidget(self.ml_classifier_class2_label2)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem12)
        self.ml_classifier_class2_display = QtWidgets.QLCDNumber(self.scrollAreaWidgetContents_2)
        self.ml_classifier_class2_display.setObjectName("ml_classifier_class2_display")
        self.horizontalLayout.addWidget(self.ml_classifier_class2_display)
        self.ml_classifier_layout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.ml_row1.addLayout(self.ml_classifier_layout)
        self.gridLayout_8.addLayout(self.ml_row1, 2, 0, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_8, 0, 0, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_5.addWidget(self.scrollArea_2, 0, 0, 1, 1)
        self.Display.addTab(self.Camera, "")
        self.gridLayout_10.addWidget(self.Display, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.Display.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.stepper1Pos_label.setText(_translate("Form", "Poistion"))
        self.label.setText(_translate("Form", "Stepper Motor 1"))
        self.stepper2Fault_boolLabel.setText(_translate("Form", "TextLabel"))
        self.stepper2Speed_label.setText(_translate("Form", "Speed"))
        self.stepper2Fault_label.setText(_translate("Form", "Fault"))
        self.stepper2ControlMode_label.setText(_translate("Form", "Control Mode"))
        self.stepper2Pos_label.setText(_translate("Form", "Position"))
        self.label_2.setText(_translate("Form", "Stepper Motor 2"))
        self.stepper1Fault_boolLabel.setText(_translate("Form", "TextLabel"))
        self.stepper1Fault_label.setText(_translate("Form", "Fault"))
        self.stepper1ControlMode_label.setText(_translate("Form", "Control Mode"))
        self.stepper1Speed_label.setText(_translate("Form", "Speed"))
        self.io_shutdown_button.setText(_translate("Form", "Shutdown"))
        self.contMotorSpeed_label.setText(_translate("Form", "ContMotorSpeed"))
        self.laserState_label.setText(_translate("Form", "Laser State"))
        self.send_button.setText(_translate("Form", "Send"))
        self.ledState_label.setText(_translate("Form", "Led State"))
        self.ccdSensorSnap_label.setText(_translate("Form", "CCD Sensor snap"))
        self.coolerState_label.setText(_translate("Form", "Cooler State"))
        self.coolerState_bool.setText(_translate("Form", "TextLabel"))
        self.gripperState_label.setText(_translate("Form", "Gripper State"))
        self.peltierState_label.setText(_translate("Form", "Peltier State"))
        self.Display.setTabText(self.Display.indexOf(self.Control), _translate("Form", "Control"))
        self.microcamera_image_label.setText(_translate("Form", "Microcamera Image"))
        self.ccd_image_label.setText(_translate("Form", "CCD Image"))
        self.ml_classifier_label.setText(_translate("Form", "ML Classifier"))
        self.ml_classifier_class1_label1.setText(_translate("Form", "class1"))
        self.ml_classifier_class1_label2.setText(_translate("Form", "TextLabel"))
        self.ml_classifier_class2_label1.setText(_translate("Form", "class2"))
        self.ml_classifier_class2_label2.setText(_translate("Form", "TextLabel"))
        self.Display.setTabText(self.Display.indexOf(self.Camera), _translate("Form", "Camera"))

