# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'science_tab_layout.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Science(QtWidgets.QWidget):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(566, 477)
        self.gridLayout_7 = QtWidgets.QGridLayout(Form)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.Display = QtWidgets.QTabWidget(Form)
        self.Display.setTabPosition(QtWidgets.QTabWidget.West)
        self.Display.setObjectName("Display")
        self.Control = QtWidgets.QWidget()
        self.Control.setObjectName("Control")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.Control)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.stepperMotor1Pos_value = QtWidgets.QLCDNumber(self.Control)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepperMotor1Pos_value.sizePolicy().hasHeightForWidth())
        self.stepperMotor1Pos_value.setSizePolicy(sizePolicy)
        self.stepperMotor1Pos_value.setMaximumSize(QtCore.QSize(16777215, 50))
        self.stepperMotor1Pos_value.setObjectName("stepperMotor1Pos_value")
        self.gridLayout_4.addWidget(self.stepperMotor1Pos_value, 5, 0, 1, 1)
        self.stepperMotor2Pos_label = QtWidgets.QLabel(self.Control)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepperMotor2Pos_label.sizePolicy().hasHeightForWidth())
        self.stepperMotor2Pos_label.setSizePolicy(sizePolicy)
        self.stepperMotor2Pos_label.setMaximumSize(QtCore.QSize(16777215, 35))
        self.stepperMotor2Pos_label.setObjectName("stepperMotor2Pos_label")
        self.gridLayout_4.addWidget(self.stepperMotor2Pos_label, 4, 2, 1, 1)
        self.Stepper1Label_2 = QtWidgets.QLabel(self.Control)
        self.Stepper1Label_2.setMaximumSize(QtCore.QSize(16777215, 35))
        self.Stepper1Label_2.setObjectName("Stepper1Label_2")
        self.gridLayout_4.addWidget(self.Stepper1Label_2, 3, 2, 1, 1)
        self.line_9 = QtWidgets.QFrame(self.Control)
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.gridLayout_4.addWidget(self.line_9, 3, 1, 5, 1)
        self.stepperMotor2Pos_value = QtWidgets.QLCDNumber(self.Control)
        self.stepperMotor2Pos_value.setMaximumSize(QtCore.QSize(16777215, 50))
        self.stepperMotor2Pos_value.setObjectName("stepperMotor2Pos_value")
        self.gridLayout_4.addWidget(self.stepperMotor2Pos_value, 5, 2, 1, 1)
        self.gridLayout_18 = QtWidgets.QGridLayout()
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.gridLayout_19 = QtWidgets.QGridLayout()
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.stepperMotor2Speed_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.Control)
        self.stepperMotor2Speed_doubleSpinBox.setObjectName("stepperMotor2Speed_doubleSpinBox")
        self.gridLayout_19.addWidget(self.stepperMotor2Speed_doubleSpinBox, 2, 0, 1, 2)
        self.line_6 = QtWidgets.QFrame(self.Control)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_19.addWidget(self.line_6, 6, 0, 1, 2)
        self.stepper2ControlMode_label = QtWidgets.QLabel(self.Control)
        self.stepper2ControlMode_label.setMaximumSize(QtCore.QSize(16777215, 35))
        self.stepper2ControlMode_label.setObjectName("stepper2ControlMode_label")
        self.gridLayout_19.addWidget(self.stepper2ControlMode_label, 4, 0, 1, 1)
        self.stepperMotor2Speed_label = QtWidgets.QLabel(self.Control)
        self.stepperMotor2Speed_label.setMaximumSize(QtCore.QSize(16777215, 35))
        self.stepperMotor2Speed_label.setObjectName("stepperMotor2Speed_label")
        self.gridLayout_19.addWidget(self.stepperMotor2Speed_label, 1, 0, 1, 1)
        self.stepper2Fault_label = QtWidgets.QLabel(self.Control)
        self.stepper2Fault_label.setMaximumSize(QtCore.QSize(16777215, 50))
        self.stepper2Fault_label.setObjectName("stepper2Fault_label")
        self.gridLayout_19.addWidget(self.stepper2Fault_label, 7, 0, 1, 1)
        self.stepper2ControlMode_spinBox = QtWidgets.QSpinBox(self.Control)
        self.stepper2ControlMode_spinBox.setObjectName("stepper2ControlMode_spinBox")
        self.gridLayout_19.addWidget(self.stepper2ControlMode_spinBox, 5, 0, 1, 2)
        self.line_7 = QtWidgets.QFrame(self.Control)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout_19.addWidget(self.line_7, 3, 0, 1, 2)
        self.stepper2Fault_bool = QtWidgets.QLabel(self.Control)
        self.stepper2Fault_bool.setMaximumSize(QtCore.QSize(16777215, 50))
        self.stepper2Fault_bool.setObjectName("stepper2Fault_bool")
        self.gridLayout_19.addWidget(self.stepper2Fault_bool, 7, 1, 1, 1)
        self.line_8 = QtWidgets.QFrame(self.Control)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout_19.addWidget(self.line_8, 0, 0, 1, 2)
        self.gridLayout_18.addLayout(self.gridLayout_19, 1, 0, 1, 2)
        self.gridLayout_4.addLayout(self.gridLayout_18, 7, 2, 1, 1)
        self.Stepper1Label = QtWidgets.QLabel(self.Control)
        self.Stepper1Label.setMaximumSize(QtCore.QSize(16777215, 35))
        self.Stepper1Label.setObjectName("Stepper1Label")
        self.gridLayout_4.addWidget(self.Stepper1Label, 3, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.ledState_label = QtWidgets.QLabel(self.Control)
        self.ledState_label.setMinimumSize(QtCore.QSize(0, 30))
        self.ledState_label.setMaximumSize(QtCore.QSize(16777215, 75))
        self.ledState_label.setObjectName("ledState_label")
        self.horizontalLayout_6.addWidget(self.ledState_label)
        self.ledState_toggle = QtWidgets.QPushButton(self.Control)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ledState_toggle.sizePolicy().hasHeightForWidth())
        self.ledState_toggle.setSizePolicy(sizePolicy)
        self.ledState_toggle.setMinimumSize(QtCore.QSize(60, 30))
        self.ledState_toggle.setStyleSheet("QPushButton{\n"
"    border-image: url(:/buttons/off.png);\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    border-image: url(:/buttons/on.png);\n"
"}")
        self.ledState_toggle.setText("")
        self.ledState_toggle.setCheckable(True)
        self.ledState_toggle.setObjectName("ledState_toggle")
        self.horizontalLayout_6.addWidget(self.ledState_toggle)
        self.gridLayout_4.addLayout(self.horizontalLayout_6, 10, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.gripperState_label = QtWidgets.QLabel(self.Control)
        self.gripperState_label.setMinimumSize(QtCore.QSize(0, 30))
        self.gripperState_label.setMaximumSize(QtCore.QSize(16777215, 75))
        self.gripperState_label.setObjectName("gripperState_label")
        self.horizontalLayout_7.addWidget(self.gripperState_label)
        self.gripperState_toggle = QtWidgets.QPushButton(self.Control)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gripperState_toggle.sizePolicy().hasHeightForWidth())
        self.gripperState_toggle.setSizePolicy(sizePolicy)
        self.gripperState_toggle.setMinimumSize(QtCore.QSize(60, 30))
        self.gripperState_toggle.setStyleSheet("QPushButton{\n"
"    border-image: url(:/buttons/off.png);\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    border-image: url(:/buttons/on.png);\n"
"}")
        self.gripperState_toggle.setText("")
        self.gripperState_toggle.setCheckable(True)
        self.gripperState_toggle.setObjectName("gripperState_toggle")
        self.horizontalLayout_7.addWidget(self.gripperState_toggle)
        self.gridLayout_4.addLayout(self.horizontalLayout_7, 11, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.laserState_label = QtWidgets.QLabel(self.Control)
        self.laserState_label.setMinimumSize(QtCore.QSize(0, 30))
        self.laserState_label.setMaximumSize(QtCore.QSize(16777215, 75))
        self.laserState_label.setObjectName("laserState_label")
        self.horizontalLayout_5.addWidget(self.laserState_label)
        self.laserState_toggle = QtWidgets.QPushButton(self.Control)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.laserState_toggle.sizePolicy().hasHeightForWidth())
        self.laserState_toggle.setSizePolicy(sizePolicy)
        self.laserState_toggle.setMinimumSize(QtCore.QSize(60, 30))
        self.laserState_toggle.setStyleSheet("QPushButton{\n"
"    border-image: url(:/buttons/off.png);\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    border-image: url(:/buttons/on.png);\n"
"}")
        self.laserState_toggle.setText("")
        self.laserState_toggle.setCheckable(True)
        self.laserState_toggle.setObjectName("laserState_toggle")
        self.horizontalLayout_5.addWidget(self.laserState_toggle)
        self.gridLayout_4.addLayout(self.horizontalLayout_5, 9, 0, 1, 1)
        self.stepperMotor1Pos_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.Control)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepperMotor1Pos_doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.stepperMotor1Pos_doubleSpinBox.setSizePolicy(sizePolicy)
        self.stepperMotor1Pos_doubleSpinBox.setObjectName("stepperMotor1Pos_doubleSpinBox")
        self.gridLayout_4.addWidget(self.stepperMotor1Pos_doubleSpinBox, 6, 0, 1, 1)
        self.io_shutdown_button = QtWidgets.QPushButton(self.Control)
        self.io_shutdown_button.setObjectName("io_shutdown_button")
        self.gridLayout_4.addWidget(self.io_shutdown_button, 0, 0, 1, 3)
        self.line_2 = QtWidgets.QFrame(self.Control)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_4.addWidget(self.line_2, 13, 0, 1, 3)
        self.gridLayout_16 = QtWidgets.QGridLayout()
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.gridLayout_17 = QtWidgets.QGridLayout()
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.stepperMotor1Speed_label = QtWidgets.QLabel(self.Control)
        self.stepperMotor1Speed_label.setMaximumSize(QtCore.QSize(16777215, 35))
        self.stepperMotor1Speed_label.setObjectName("stepperMotor1Speed_label")
        self.gridLayout_17.addWidget(self.stepperMotor1Speed_label, 1, 0, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.Control)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_17.addWidget(self.line_4, 3, 0, 1, 2)
        self.line_3 = QtWidgets.QFrame(self.Control)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_17.addWidget(self.line_3, 0, 0, 1, 2)
        self.stepper1ControlMode_label = QtWidgets.QLabel(self.Control)
        self.stepper1ControlMode_label.setMaximumSize(QtCore.QSize(16777215, 35))
        self.stepper1ControlMode_label.setObjectName("stepper1ControlMode_label")
        self.gridLayout_17.addWidget(self.stepper1ControlMode_label, 4, 0, 1, 1)
        self.stepperMotor1Speed_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.Control)
        self.stepperMotor1Speed_doubleSpinBox.setObjectName("stepperMotor1Speed_doubleSpinBox")
        self.gridLayout_17.addWidget(self.stepperMotor1Speed_doubleSpinBox, 2, 0, 1, 2)
        self.stepper1ControlMode_spinBox = QtWidgets.QSpinBox(self.Control)
        self.stepper1ControlMode_spinBox.setObjectName("stepper1ControlMode_spinBox")
        self.gridLayout_17.addWidget(self.stepper1ControlMode_spinBox, 5, 0, 1, 2)
        self.stepper1Fault_label = QtWidgets.QLabel(self.Control)
        self.stepper1Fault_label.setMaximumSize(QtCore.QSize(16777215, 50))
        self.stepper1Fault_label.setObjectName("stepper1Fault_label")
        self.gridLayout_17.addWidget(self.stepper1Fault_label, 7, 0, 1, 1)
        self.stepper1Fault_bool = QtWidgets.QLabel(self.Control)
        self.stepper1Fault_bool.setMaximumSize(QtCore.QSize(16777215, 50))
        self.stepper1Fault_bool.setObjectName("stepper1Fault_bool")
        self.gridLayout_17.addWidget(self.stepper1Fault_bool, 7, 1, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.Control)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_17.addWidget(self.line_5, 6, 0, 1, 2)
        self.gridLayout_16.addLayout(self.gridLayout_17, 5, 0, 1, 2)
        self.gridLayout_4.addLayout(self.gridLayout_16, 7, 0, 1, 1)
        self.stepperMotor1Pos_label = QtWidgets.QLabel(self.Control)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepperMotor1Pos_label.sizePolicy().hasHeightForWidth())
        self.stepperMotor1Pos_label.setSizePolicy(sizePolicy)
        self.stepperMotor1Pos_label.setMaximumSize(QtCore.QSize(16777215, 35))
        self.stepperMotor1Pos_label.setObjectName("stepperMotor1Pos_label")
        self.gridLayout_4.addWidget(self.stepperMotor1Pos_label, 4, 0, 1, 1)
        self.stepperMotor2Pos_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.Control)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepperMotor2Pos_doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.stepperMotor2Pos_doubleSpinBox.setSizePolicy(sizePolicy)
        self.stepperMotor2Pos_doubleSpinBox.setObjectName("stepperMotor2Pos_doubleSpinBox")
        self.gridLayout_4.addWidget(self.stepperMotor2Pos_doubleSpinBox, 6, 2, 1, 1)
        self.line = QtWidgets.QFrame(self.Control)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_4.addWidget(self.line, 1, 0, 1, 3)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.coolerState_label = QtWidgets.QLabel(self.Control)
        self.coolerState_label.setMinimumSize(QtCore.QSize(0, 30))
        self.coolerState_label.setMaximumSize(QtCore.QSize(16777215, 75))
        self.coolerState_label.setObjectName("coolerState_label")
        self.horizontalLayout_8.addWidget(self.coolerState_label)
        self.coolerState_bool = QtWidgets.QLabel(self.Control)
        self.coolerState_bool.setMinimumSize(QtCore.QSize(0, 30))
        self.coolerState_bool.setMaximumSize(QtCore.QSize(16777215, 75))
        self.coolerState_bool.setObjectName("coolerState_bool")
        self.horizontalLayout_8.addWidget(self.coolerState_bool)
        self.gridLayout_4.addLayout(self.horizontalLayout_8, 9, 2, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.peltierState_label = QtWidgets.QLabel(self.Control)
        self.peltierState_label.setMinimumSize(QtCore.QSize(0, 30))
        self.peltierState_label.setMaximumSize(QtCore.QSize(16777215, 75))
        self.peltierState_label.setObjectName("peltierState_label")
        self.horizontalLayout_9.addWidget(self.peltierState_label)
        self.peltierState_toggle = QtWidgets.QPushButton(self.Control)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.peltierState_toggle.sizePolicy().hasHeightForWidth())
        self.peltierState_toggle.setSizePolicy(sizePolicy)
        self.peltierState_toggle.setMinimumSize(QtCore.QSize(60, 30))
        self.peltierState_toggle.setStyleSheet("QPushButton{\n"
"    border-image: url(:/buttons/off.png);\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    border-image: url(:/buttons/on.png);\n"
"}")
        self.peltierState_toggle.setText("")
        self.peltierState_toggle.setCheckable(True)
        self.peltierState_toggle.setObjectName("peltierState_toggle")
        self.horizontalLayout_9.addWidget(self.peltierState_toggle)
        self.gridLayout_4.addLayout(self.horizontalLayout_9, 10, 2, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.ccdSensorSnap_label = QtWidgets.QLabel(self.Control)
        self.ccdSensorSnap_label.setMinimumSize(QtCore.QSize(0, 30))
        self.ccdSensorSnap_label.setMaximumSize(QtCore.QSize(16777215, 75))
        self.ccdSensorSnap_label.setObjectName("ccdSensorSnap_label")
        self.horizontalLayout_10.addWidget(self.ccdSensorSnap_label)
        self.ccdSensorSnap_toggle = QtWidgets.QPushButton(self.Control)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ccdSensorSnap_toggle.sizePolicy().hasHeightForWidth())
        self.ccdSensorSnap_toggle.setSizePolicy(sizePolicy)
        self.ccdSensorSnap_toggle.setMinimumSize(QtCore.QSize(60, 30))
        self.ccdSensorSnap_toggle.setStyleSheet("QPushButton{\n"
"    border-image: url(:/buttons/off.png);\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    border-image: url(:/buttons/on.png);\n"
"}")
        self.ccdSensorSnap_toggle.setText("")
        self.ccdSensorSnap_toggle.setCheckable(True)
        self.ccdSensorSnap_toggle.setObjectName("ccdSensorSnap_toggle")
        self.horizontalLayout_10.addWidget(self.ccdSensorSnap_toggle)
        self.gridLayout_4.addLayout(self.horizontalLayout_10, 11, 2, 1, 1)
        self.line_10 = QtWidgets.QFrame(self.Control)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.gridLayout_4.addWidget(self.line_10, 8, 0, 1, 3)
        self.Display.addTab(self.Control, "")
        self.Camera = QtWidgets.QWidget()
        self.Camera.setObjectName("Camera")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.Camera)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.Camera)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 698, 785))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.microcamera_image_label = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.microcamera_image_label.setObjectName("microcamera_image_label")
        self.verticalLayout_3.addWidget(self.microcamera_image_label)
        self.microcamera_image_graphicsView = QtWidgets.QGraphicsView(self.scrollAreaWidgetContents_2)
        self.microcamera_image_graphicsView.setObjectName("microcamera_image_graphicsView")
        self.verticalLayout_3.addWidget(self.microcamera_image_graphicsView)
        self.gridLayout_5.addLayout(self.verticalLayout_3, 1, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ccd_image_label = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.ccd_image_label.setObjectName("ccd_image_label")
        self.verticalLayout_2.addWidget(self.ccd_image_label)
        self.ccd_image_graphicsView = QtWidgets.QGraphicsView(self.scrollAreaWidgetContents_2)
        self.ccd_image_graphicsView.setObjectName("ccd_image_graphicsView")
        self.verticalLayout_2.addWidget(self.ccd_image_graphicsView)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.gridLayout_5.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.ml_row1 = QtWidgets.QVBoxLayout()
        self.ml_row1.setObjectName("ml_row1")
        self.ml_classifier_label = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.ml_classifier_label.setObjectName("ml_classifier_label")
        self.ml_row1.addWidget(self.ml_classifier_label)
        self.line_29 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_29.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_29.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_29.setObjectName("line_29")
        self.ml_row1.addWidget(self.line_29)
        self.ml_classifier_layout = QtWidgets.QFormLayout()
        self.ml_classifier_layout.setObjectName("ml_classifier_layout")
        self.ml_classifier_class1_label1 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.ml_classifier_class1_label1.setObjectName("ml_classifier_class1_label1")
        self.ml_classifier_layout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.ml_classifier_class1_label1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ml_classifier_class1_label2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.ml_classifier_class1_label2.setObjectName("ml_classifier_class1_label2")
        self.horizontalLayout_2.addWidget(self.ml_classifier_class1_label2)
        self.line_27 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_27.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_27.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_27.setObjectName("line_27")
        self.horizontalLayout_2.addWidget(self.line_27)
        self.ml_classifier_class1_display = QtWidgets.QLCDNumber(self.scrollAreaWidgetContents_2)
        self.ml_classifier_class1_display.setObjectName("ml_classifier_class1_display")
        self.horizontalLayout_2.addWidget(self.ml_classifier_class1_display)
        self.ml_classifier_layout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.ml_classifier_class2_label1 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.ml_classifier_class2_label1.setObjectName("ml_classifier_class2_label1")
        self.ml_classifier_layout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.ml_classifier_class2_label1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ml_classifier_class2_label2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.ml_classifier_class2_label2.setObjectName("ml_classifier_class2_label2")
        self.horizontalLayout.addWidget(self.ml_classifier_class2_label2)
        self.line_28 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_28.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_28.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_28.setObjectName("line_28")
        self.horizontalLayout.addWidget(self.line_28)
        self.ml_classifier_class2_display = QtWidgets.QLCDNumber(self.scrollAreaWidgetContents_2)
        self.ml_classifier_class2_display.setObjectName("ml_classifier_class2_display")
        self.horizontalLayout.addWidget(self.ml_classifier_class2_display)
        self.ml_classifier_layout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.ml_row1.addLayout(self.ml_classifier_layout)
        self.gridLayout_5.addLayout(self.ml_row1, 2, 0, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_6.addWidget(self.scrollArea_2, 0, 0, 1, 1)
        self.Display.addTab(self.Camera, "")
        self.gridLayout_7.addWidget(self.Display, 0, 1, 1, 1)

        self.retranslateUi(Form)
        self.Display.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.stepperMotor2Pos_label.setText(_translate("Form", "Stepper Motor 2 (pos)"))
        self.Stepper1Label_2.setText(_translate("Form", "Stepper Motor 2"))
        self.stepper2ControlMode_label.setText(_translate("Form", "Stepper 2 Control Mode"))
        self.stepperMotor2Speed_label.setText(_translate("Form", "Stepper Motor 2 Speed"))
        self.stepper2Fault_label.setText(_translate("Form", "Stepper 2 Fault"))
        self.stepper2Fault_bool.setText(_translate("Form", "TextLabel"))
        self.Stepper1Label.setText(_translate("Form", "Stepper Motor 1"))
        self.ledState_label.setText(_translate("Form", "Led State"))
        self.gripperState_label.setText(_translate("Form", "Gripper State"))
        self.laserState_label.setText(_translate("Form", "Laser State"))
        self.io_shutdown_button.setText(_translate("Form", "Shutdown"))
        self.stepperMotor1Speed_label.setText(_translate("Form", "Stepper Motor 1 Speed"))
        self.stepper1ControlMode_label.setText(_translate("Form", "Stepper 1 Control Mode"))
        self.stepper1Fault_label.setText(_translate("Form", "Stepper 1 Fault"))
        self.stepper1Fault_bool.setText(_translate("Form", "TextLabel"))
        self.stepperMotor1Pos_label.setText(_translate("Form", "Stepper Motor 1 (pos)"))
        self.coolerState_label.setText(_translate("Form", "Cooler State"))
        self.coolerState_bool.setText(_translate("Form", "TextLabel"))
        self.peltierState_label.setText(_translate("Form", "Peltier State"))
        self.ccdSensorSnap_label.setText(_translate("Form", "CCD Sensor snap"))
        self.Display.setTabText(self.Display.indexOf(self.Control), _translate("Form", "Control"))
        self.microcamera_image_label.setText(_translate("Form", "Microcamera Image"))
        self.ccd_image_label.setText(_translate("Form", "CCD Image"))
        self.ml_classifier_label.setText(_translate("Form", "ML Classifier"))
        self.ml_classifier_class1_label1.setText(_translate("Form", "class1"))
        self.ml_classifier_class1_label2.setText(_translate("Form", "TextLabel"))
        self.ml_classifier_class2_label1.setText(_translate("Form", "class2"))
        self.ml_classifier_class2_label2.setText(_translate("Form", "TextLabel"))
        self.Display.setTabText(self.Display.indexOf(self.Camera), _translate("Form", "Camera"))
import buttons_rc
