# Goal tolerance parameters
xy_goal_tolerance: 0.2
yaw_goal_tolerance: 0.2
free_goal_vel: false

# Trajectory configuration parameters
dt_ref: 0.3
dt_hysteresis: 0.1
min_samples: 3
global_plan_overwrite_orientation: true
global_plan_viapoint_sep: -0.1
max_global_plan_lookahead_dist: 3.0
force_reinit_new_goal_dist: 1.0
feasibility_check_no_poses: 4
publish_feedback: false
shrink_horizon_backup: true
allow_init_with_backwards_motion: false
exact_arc_length: false
shrink_horizon_min_duration: 10.0

# Obstacle parameters
min_obstacle_dist: 0.5
include_costmap_obstacles: true
costmap_obstacles_behind_robot_dist: 1.0
obstacle_poses_affected: 30
inflation_dist: 0.0
include_dynamic_obstacles: false
legacy_obstacle_association: false
obstalce_association_force_inclusion_factor: 1.5
obstacle_association_cutoff_factor: 5

costmap_converter_plugin: ""
costmap_converter_spin_thread: true
costmap_converter_rate: 5.0

# Optimization parameters
no_inner_iterations: 5
no_outer_iterations: 4
penalty_epsilon: 0.1
weight_max_vel_x: 2.0
weight_max_vel_theta: 1.0
weight_acc_lim_x: 1.0
weight_acc_lim_theta: 1.0
weight_kinematics_nh: 1000.0
weight_kinematics_forward_drive: 1.0
weight_kinematics_turning_radius: 1.0
weight_optimaltime: 1.0
weight_obstacle: 50.0
weight_viapoint: 1.0
weight_inflation: 0.1
weight_adept_factor: 2.0

# Parallel planning in distinctive topologies params
enable_homotopy_class_planning: true
enable_multithreading: true
max_number_classes: 4
selection_cost_hysteresis: 1.0
selection_obst_cost_scale: 100.0
selection_viapoint_cost_scale: 1.0
selection_alternative_time_cost: false 
roadmap_graph_no_samples: 15
roadmap_graph_area_width: 6
h_signature_prescaler: 1.0
h_signature_threshold: 0.1
obstacle_heading_threshold: 1.0
visualize_hc_graph: false
viapoints_all_candidates: true
switching_blocking_period: 0.0

# Miscellaneous parameters
odom_topic: "odom"
map_frame: "odom"