# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'arm_layout.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_Arm(object):
    def setupUi(self, Arm):
        if not Arm.objectName():
            Arm.setObjectName(u"Arm")
        Arm.resize(308, 475)
        self.arm_joints = QLabel(Arm)
        self.arm_joints.setObjectName(u"arm_joints")
        self.arm_joints.setGeometry(QRect(10, 10, 121, 41))
        font = QFont()
        font.setPointSize(17)
        self.arm_joints.setFont(font)
        self.joint_one = QLabel(Arm)
        self.joint_one.setObjectName(u"joint_one")
        self.joint_one.setGeometry(QRect(10, 60, 21, 17))
        self.joint_one_value = QLCDNumber(Arm)
        self.joint_one_value.setObjectName(u"joint_one_value")
        self.joint_one_value.setGeometry(QRect(10, 80, 71, 31))
        self.joint_two_value = QLCDNumber(Arm)
        self.joint_two_value.setObjectName(u"joint_two_value")
        self.joint_two_value.setGeometry(QRect(120, 80, 71, 31))
        self.joint_two = QLabel(Arm)
        self.joint_two.setObjectName(u"joint_two")
        self.joint_two.setGeometry(QRect(120, 60, 21, 17))
        self.joint_three_value = QLCDNumber(Arm)
        self.joint_three_value.setObjectName(u"joint_three_value")
        self.joint_three_value.setGeometry(QRect(230, 80, 71, 31))
        self.joint_three = QLabel(Arm)
        self.joint_three.setObjectName(u"joint_three")
        self.joint_three.setGeometry(QRect(230, 60, 21, 17))
        self.joint_four_value = QLCDNumber(Arm)
        self.joint_four_value.setObjectName(u"joint_four_value")
        self.joint_four_value.setGeometry(QRect(10, 150, 71, 31))
        self.joint_five_value = QLCDNumber(Arm)
        self.joint_five_value.setObjectName(u"joint_five_value")
        self.joint_five_value.setGeometry(QRect(120, 150, 71, 31))
        self.joint_five = QLabel(Arm)
        self.joint_five.setObjectName(u"joint_five")
        self.joint_five.setGeometry(QRect(120, 130, 21, 17))
        self.joint_four = QLabel(Arm)
        self.joint_four.setObjectName(u"joint_four")
        self.joint_four.setGeometry(QRect(10, 130, 21, 17))
        self.error_label = QLabel(Arm)
        self.error_label.setObjectName(u"error_label")
        self.error_label.setEnabled(True)
        self.error_label.setGeometry(QRect(10, 210, 91, 31))
        font1 = QFont()
        font1.setPointSize(20)
        font1.setBold(True)
        font1.setWeight(75)
        self.error_label.setFont(font1)
        self.error_label.setAutoFillBackground(False)
        self.error_label.setStyleSheet(u"QLabel {background:red}\n"
"")
        self.hand_position_label = QLabel(Arm)
        self.hand_position_label.setObjectName(u"hand_position_label")
        self.hand_position_label.setGeometry(QRect(10, 250, 151, 41))
        self.hand_position_label.setFont(font)
        self.hand_position_label_2 = QLabel(Arm)
        self.hand_position_label_2.setObjectName(u"hand_position_label_2")
        self.hand_position_label_2.setGeometry(QRect(10, 360, 151, 41))
        self.hand_position_label_2.setFont(font)
        self.hand_x = QLabel(Arm)
        self.hand_x.setObjectName(u"hand_x")
        self.hand_x.setGeometry(QRect(40, 290, 21, 17))
        font2 = QFont()
        font2.setPointSize(14)
        self.hand_x.setFont(font2)
        self.hand_y = QLabel(Arm)
        self.hand_y.setObjectName(u"hand_y")
        self.hand_y.setGeometry(QRect(150, 290, 31, 21))
        self.hand_y.setFont(font2)
        self.hand_z = QLabel(Arm)
        self.hand_z.setObjectName(u"hand_z")
        self.hand_z.setGeometry(QRect(250, 290, 21, 17))
        self.hand_z.setFont(font2)
        self.orientation_z_val = QLCDNumber(Arm)
        self.orientation_z_val.setObjectName(u"orientation_z_val")
        self.orientation_z_val.setGeometry(QRect(230, 420, 71, 31))
        self.orientation_y_val = QLCDNumber(Arm)
        self.orientation_y_val.setObjectName(u"orientation_y_val")
        self.orientation_y_val.setGeometry(QRect(120, 420, 71, 31))
        self.orientation_x_val = QLCDNumber(Arm)
        self.orientation_x_val.setObjectName(u"orientation_x_val")
        self.orientation_x_val.setGeometry(QRect(10, 420, 71, 31))
        self.hand_z_val = QLCDNumber(Arm)
        self.hand_z_val.setObjectName(u"hand_z_val")
        self.hand_z_val.setGeometry(QRect(230, 310, 71, 31))
        self.hand_y_val = QLCDNumber(Arm)
        self.hand_y_val.setObjectName(u"hand_y_val")
        self.hand_y_val.setGeometry(QRect(120, 310, 71, 31))
        self.hand_x_val = QLCDNumber(Arm)
        self.hand_x_val.setObjectName(u"hand_x_val")
        self.hand_x_val.setGeometry(QRect(10, 310, 71, 31))
        self.orientation_y = QLabel(Arm)
        self.orientation_y.setObjectName(u"orientation_y")
        self.orientation_y.setGeometry(QRect(150, 400, 31, 21))
        self.orientation_y.setFont(font2)
        self.orientation_x = QLabel(Arm)
        self.orientation_x.setObjectName(u"orientation_x")
        self.orientation_x.setGeometry(QRect(40, 400, 21, 17))
        self.orientation_x.setFont(font2)
        self.orientation_z = QLabel(Arm)
        self.orientation_z.setObjectName(u"orientation_z")
        self.orientation_z.setGeometry(QRect(250, 400, 21, 17))
        self.orientation_z.setFont(font2)

        self.retranslateUi(Arm)

        QMetaObject.connectSlotsByName(Arm)
    # setupUi

    def retranslateUi(self, Arm):
        Arm.setWindowTitle(QCoreApplication.translate("Arm", u"Form", None))
        self.arm_joints.setText(QCoreApplication.translate("Arm", u"Arm Joints", None))
        self.joint_one.setText(QCoreApplication.translate("Arm", u"#1", None))
        self.joint_two.setText(QCoreApplication.translate("Arm", u"#1", None))
        self.joint_three.setText(QCoreApplication.translate("Arm", u"#1", None))
        self.joint_five.setText(QCoreApplication.translate("Arm", u"#1", None))
        self.joint_four.setText(QCoreApplication.translate("Arm", u"#1", None))
        self.error_label.setText(QCoreApplication.translate("Arm", u"Error", None))
        self.hand_position_label.setText(QCoreApplication.translate("Arm", u"Hand Position", None))
        self.hand_position_label_2.setText(QCoreApplication.translate("Arm", u"Orientation", None))
        self.hand_x.setText(QCoreApplication.translate("Arm", u"X:", None))
        self.hand_y.setText(QCoreApplication.translate("Arm", u"Y:", None))
        self.hand_z.setText(QCoreApplication.translate("Arm", u"Z:", None))
        self.orientation_y.setText(QCoreApplication.translate("Arm", u"Y:", None))
        self.orientation_x.setText(QCoreApplication.translate("Arm", u"X:", None))
        self.orientation_z.setText(QCoreApplication.translate("Arm", u"Z:", None))
    # retranslateUi

