# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'arm_layout.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_Arm(object):
    def setupUi(self, Arm):
        if not Arm.objectName():
            Arm.setObjectName(u"Arm")
        Arm.resize(368, 619)
        Arm.setAutoFillBackground(True)
        self.arm_joints = QLabel(Arm)
        self.arm_joints.setObjectName(u"arm_joints")
        self.arm_joints.setGeometry(QRect(10, 10, 121, 41))
        font = QFont()
        font.setPointSize(17)
        self.arm_joints.setFont(font)
        self.joint_Shoulder = QLabel(Arm)
        self.joint_Shoulder.setObjectName(u"joint_Shoulder")
        self.joint_Shoulder.setGeometry(QRect(120, 60, 71, 17))
        self.joint_one_value = QLCDNumber(Arm)
        self.joint_one_value.setObjectName(u"joint_one_value")
        self.joint_one_value.setGeometry(QRect(10, 80, 71, 31))
        self.joint_two_value = QLCDNumber(Arm)
        self.joint_two_value.setObjectName(u"joint_two_value")
        self.joint_two_value.setGeometry(QRect(120, 80, 71, 31))
        self.joint_Elbow = QLabel(Arm)
        self.joint_Elbow.setObjectName(u"joint_Elbow")
        self.joint_Elbow.setGeometry(QRect(230, 60, 71, 16))
        self.joint_three_value = QLCDNumber(Arm)
        self.joint_three_value.setObjectName(u"joint_three_value")
        self.joint_three_value.setGeometry(QRect(230, 80, 71, 31))
        self.joint_Wrist = QLabel(Arm)
        self.joint_Wrist.setObjectName(u"joint_Wrist")
        self.joint_Wrist.setGeometry(QRect(10, 130, 71, 17))
        self.joint_four_value = QLCDNumber(Arm)
        self.joint_four_value.setObjectName(u"joint_four_value")
        self.joint_four_value.setGeometry(QRect(10, 150, 71, 31))
        self.joint_five_value = QLCDNumber(Arm)
        self.joint_five_value.setObjectName(u"joint_five_value")
        self.joint_five_value.setGeometry(QRect(120, 150, 71, 31))
        self.joint_End = QLabel(Arm)
        self.joint_End.setObjectName(u"joint_End")
        self.joint_End.setGeometry(QRect(120, 130, 51, 17))
        self.joint_Waist = QLabel(Arm)
        self.joint_Waist.setObjectName(u"joint_Waist")
        self.joint_Waist.setGeometry(QRect(10, 60, 61, 17))
        self.hand_position_label = QLabel(Arm)
        self.hand_position_label.setObjectName(u"hand_position_label")
        self.hand_position_label.setGeometry(QRect(10, 250, 151, 41))
        self.hand_position_label.setFont(font)
        self.orientation_label = QLabel(Arm)
        self.orientation_label.setObjectName(u"orientation_label")
        self.orientation_label.setGeometry(QRect(10, 360, 151, 41))
        self.orientation_label.setFont(font)
        self.hand_x = QLabel(Arm)
        self.hand_x.setObjectName(u"hand_x")
        self.hand_x.setGeometry(QRect(40, 290, 21, 17))
        font1 = QFont()
        font1.setPointSize(14)
        self.hand_x.setFont(font1)
        self.hand_y = QLabel(Arm)
        self.hand_y.setObjectName(u"hand_y")
        self.hand_y.setGeometry(QRect(150, 290, 31, 21))
        self.hand_y.setFont(font1)
        self.hand_z = QLabel(Arm)
        self.hand_z.setObjectName(u"hand_z")
        self.hand_z.setGeometry(QRect(250, 290, 21, 17))
        self.hand_z.setFont(font1)
        self.orientation_z_val = QLCDNumber(Arm)
        self.orientation_z_val.setObjectName(u"orientation_z_val")
        self.orientation_z_val.setGeometry(QRect(230, 420, 71, 31))
        self.orientation_y_val = QLCDNumber(Arm)
        self.orientation_y_val.setObjectName(u"orientation_y_val")
        self.orientation_y_val.setGeometry(QRect(120, 420, 71, 31))
        self.orientation_x_val = QLCDNumber(Arm)
        self.orientation_x_val.setObjectName(u"orientation_x_val")
        self.orientation_x_val.setGeometry(QRect(10, 420, 71, 31))
        self.hand_z_val = QLCDNumber(Arm)
        self.hand_z_val.setObjectName(u"hand_z_val")
        self.hand_z_val.setGeometry(QRect(230, 310, 71, 31))
        self.hand_y_val = QLCDNumber(Arm)
        self.hand_y_val.setObjectName(u"hand_y_val")
        self.hand_y_val.setGeometry(QRect(120, 310, 71, 31))
        self.hand_x_val = QLCDNumber(Arm)
        self.hand_x_val.setObjectName(u"hand_x_val")
        self.hand_x_val.setGeometry(QRect(10, 310, 71, 31))
        self.orientation_y = QLabel(Arm)
        self.orientation_y.setObjectName(u"orientation_y")
        self.orientation_y.setGeometry(QRect(150, 400, 31, 21))
        self.orientation_y.setFont(font1)
        self.orientation_x = QLabel(Arm)
        self.orientation_x.setObjectName(u"orientation_x")
        self.orientation_x.setGeometry(QRect(40, 400, 21, 17))
        self.orientation_x.setFont(font1)
        self.orientation_z = QLabel(Arm)
        self.orientation_z.setObjectName(u"orientation_z")
        self.orientation_z.setGeometry(QRect(250, 400, 21, 17))
        self.orientation_z.setFont(font1)
        self.error_label = QTextBrowser(Arm)
        self.error_label.setObjectName(u"error_label")
        self.error_label.setGeometry(QRect(10, 510, 231, 91))
        self.error_message_label = QLabel(Arm)
        self.error_message_label.setObjectName(u"error_message_label")
        self.error_message_label.setGeometry(QRect(10, 460, 151, 41))
        self.error_message_label.setFont(font)

        self.retranslateUi(Arm)

        QMetaObject.connectSlotsByName(Arm)
    # setupUi

    def retranslateUi(self, Arm):
        Arm.setWindowTitle(QCoreApplication.translate("Arm", u"Form", None))
        self.arm_joints.setText(QCoreApplication.translate("Arm", u"Arm Joints", None))
        self.joint_Shoulder.setText(QCoreApplication.translate("Arm", u"#Shoulder", None))
        self.joint_Elbow.setText(QCoreApplication.translate("Arm", u"#Elbow", None))
        self.joint_Wrist.setText(QCoreApplication.translate("Arm", u"#Wrist", None))
        self.joint_End.setText(QCoreApplication.translate("Arm", u"#End ", None))
        self.joint_Waist.setText(QCoreApplication.translate("Arm", u"#Waist", None))
        self.hand_position_label.setText(QCoreApplication.translate("Arm", u"Hand Position", None))
        self.orientation_label.setText(QCoreApplication.translate("Arm", u"Orientation", None))
        self.hand_x.setText(QCoreApplication.translate("Arm", u"X:", None))
        self.hand_y.setText(QCoreApplication.translate("Arm", u"Y:", None))
        self.hand_z.setText(QCoreApplication.translate("Arm", u"Z:", None))
        self.orientation_y.setText(QCoreApplication.translate("Arm", u"Y:", None))
        self.orientation_x.setText(QCoreApplication.translate("Arm", u"X:", None))
        self.orientation_z.setText(QCoreApplication.translate("Arm", u"Z:", None))
        self.error_message_label.setText(QCoreApplication.translate("Arm", u"Error Message", None))
    # retranslateUi

