# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'drive_layout.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_Drive(object):
    def setupUi(self, Drive):
        if not Drive.objectName():
            Drive.setObjectName(u"Drive")
        Drive.resize(515, 615)
        Drive.setAutoFillBackground(True)
        self.right_speed_data = QLCDNumber(Drive)
        self.right_speed_data.setObjectName(u"right_speed_data")
        self.right_speed_data.setGeometry(QRect(120, 40, 71, 31))
        self.right_speed_data.setSegmentStyle(QLCDNumber.Flat)
        self.right_speed_label = QLabel(Drive)
        self.right_speed_label.setObjectName(u"right_speed_label")
        self.right_speed_label.setGeometry(QRect(116, 70, 91, 21))
        self.rear_left_speed_data = QLCDNumber(Drive)
        self.rear_left_speed_data.setObjectName(u"rear_left_speed_data")
        self.rear_left_speed_data.setGeometry(QRect(20, 100, 71, 31))
        self.rear_left_speed_data.setSegmentStyle(QLCDNumber.Flat)
        self.left_speed_label = QLabel(Drive)
        self.left_speed_label.setObjectName(u"left_speed_label")
        self.left_speed_label.setGeometry(QRect(20, 70, 81, 21))
        self.left_speed_data = QLCDNumber(Drive)
        self.left_speed_data.setObjectName(u"left_speed_data")
        self.left_speed_data.setGeometry(QRect(20, 40, 71, 31))
        font = QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.left_speed_data.setFont(font)
        self.left_speed_data.setSmallDecimalPoint(False)
        self.left_speed_data.setDigitCount(5)
        self.left_speed_data.setSegmentStyle(QLCDNumber.Flat)
        self.left_speed_data.setProperty("value", 0.000000000000000)
        self.left_speed_data.setProperty("intValue", 0)
        self.rear_right_speed_label = QLabel(Drive)
        self.rear_right_speed_label.setObjectName(u"rear_right_speed_label")
        self.rear_right_speed_label.setGeometry(QRect(120, 130, 91, 20))
        self.rear_right_speed_data = QLCDNumber(Drive)
        self.rear_right_speed_data.setObjectName(u"rear_right_speed_data")
        self.rear_right_speed_data.setGeometry(QRect(120, 100, 71, 31))
        self.rear_right_speed_data.setSegmentStyle(QLCDNumber.Flat)
        self.rear_left_speed_label = QLabel(Drive)
        self.rear_left_speed_label.setObjectName(u"rear_left_speed_label")
        self.rear_left_speed_label.setGeometry(QRect(20, 120, 81, 41))
        self.wheel_velocity_label = QLabel(Drive)
        self.wheel_velocity_label.setObjectName(u"wheel_velocity_label")
        self.wheel_velocity_label.setGeometry(QRect(10, 10, 231, 31))
        font1 = QFont()
        font1.setPointSize(14)
        self.wheel_velocity_label.setFont(font1)
        self.wheel_velocity_label.setScaledContents(True)
        self.twist_label = QLabel(Drive)
        self.twist_label.setObjectName(u"twist_label")
        self.twist_label.setGeometry(QRect(20, 180, 71, 16))
        self.twist_label.setFont(font1)
        self.twist_linear_velocity = QLCDNumber(Drive)
        self.twist_linear_velocity.setObjectName(u"twist_linear_velocity")
        self.twist_linear_velocity.setGeometry(QRect(20, 210, 71, 31))
        self.twist_linear_velocity.setSegmentStyle(QLCDNumber.Flat)
        self.twist_angular_velocity = QLCDNumber(Drive)
        self.twist_angular_velocity.setObjectName(u"twist_angular_velocity")
        self.twist_angular_velocity.setGeometry(QRect(100, 210, 81, 31))
        self.twist_angular_velocity.setSegmentStyle(QLCDNumber.Flat)
        self.twist_linear_velocity_label = QLabel(Drive)
        self.twist_linear_velocity_label.setObjectName(u"twist_linear_velocity_label")
        self.twist_linear_velocity_label.setGeometry(QRect(30, 250, 51, 16))
        self.twist_angular_velocity_label = QLabel(Drive)
        self.twist_angular_velocity_label.setObjectName(u"twist_angular_velocity_label")
        self.twist_angular_velocity_label.setGeometry(QRect(110, 250, 61, 21))
        self.line = QFrame(Drive)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(0, 160, 681, 16))
        font2 = QFont()
        font2.setPointSize(12)
        font2.setBold(True)
        font2.setWeight(75)
        self.line.setFont(font2)
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.line_2 = QFrame(Drive)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(0, 270, 681, 16))
        self.line_2.setFrameShape(QFrame.HLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.current_robot_location_label = QLabel(Drive)
        self.current_robot_location_label.setObjectName(u"current_robot_location_label")
        self.current_robot_location_label.setGeometry(QRect(20, 300, 231, 16))
        self.current_robot_location_label.setFont(font1)
        self.line_3 = QFrame(Drive)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(0, 460, 681, 16))
        self.line_3.setFrameShape(QFrame.HLine)
        self.line_3.setFrameShadow(QFrame.Sunken)
        self.robot_location_x = QLCDNumber(Drive)
        self.robot_location_x.setObjectName(u"robot_location_x")
        self.robot_location_x.setGeometry(QRect(20, 330, 71, 31))
        self.robot_location_x.setSegmentStyle(QLCDNumber.Flat)
        self.robot_location_y = QLCDNumber(Drive)
        self.robot_location_y.setObjectName(u"robot_location_y")
        self.robot_location_y.setGeometry(QRect(100, 330, 71, 31))
        self.robot_location_y.setSegmentStyle(QLCDNumber.Flat)
        self.robot_location_x_label = QLabel(Drive)
        self.robot_location_x_label.setObjectName(u"robot_location_x_label")
        self.robot_location_x_label.setGeometry(QRect(40, 363, 47, 20))
        self.robot_location_y_label = QLabel(Drive)
        self.robot_location_y_label.setObjectName(u"robot_location_y_label")
        self.robot_location_y_label.setGeometry(QRect(130, 360, 47, 21))
        self.robot_location_z = QLCDNumber(Drive)
        self.robot_location_z.setObjectName(u"robot_location_z")
        self.robot_location_z.setGeometry(QRect(180, 330, 71, 31))
        self.robot_location_z.setSegmentStyle(QLCDNumber.Flat)
        self.robot_location_z_label = QLabel(Drive)
        self.robot_location_z_label.setObjectName(u"robot_location_z_label")
        self.robot_location_z_label.setGeometry(QRect(200, 360, 51, 21))
        self.robot_location_roll = QLCDNumber(Drive)
        self.robot_location_roll.setObjectName(u"robot_location_roll")
        self.robot_location_roll.setGeometry(QRect(20, 390, 71, 31))
        self.robot_location_roll.setSegmentStyle(QLCDNumber.Flat)
        self.robot_location_pitch = QLCDNumber(Drive)
        self.robot_location_pitch.setObjectName(u"robot_location_pitch")
        self.robot_location_pitch.setGeometry(QRect(100, 390, 71, 31))
        self.robot_location_pitch.setSegmentStyle(QLCDNumber.Flat)
        self.robot_location_yaw = QLCDNumber(Drive)
        self.robot_location_yaw.setObjectName(u"robot_location_yaw")
        self.robot_location_yaw.setGeometry(QRect(180, 390, 71, 31))
        self.robot_location_yaw.setSegmentStyle(QLCDNumber.Flat)
        self.robot_location_roll_label = QLabel(Drive)
        self.robot_location_roll_label.setObjectName(u"robot_location_roll_label")
        self.robot_location_roll_label.setGeometry(QRect(40, 420, 47, 20))
        self.robot_location_pitch_label = QLabel(Drive)
        self.robot_location_pitch_label.setObjectName(u"robot_location_pitch_label")
        self.robot_location_pitch_label.setGeometry(QRect(130, 420, 47, 21))
        self.robot_location_yaw_label = QLabel(Drive)
        self.robot_location_yaw_label.setObjectName(u"robot_location_yaw_label")
        self.robot_location_yaw_label.setGeometry(QRect(200, 420, 51, 21))
        self.error_label = QTextBrowser(Drive)
        self.error_label.setObjectName(u"error_label")
        self.error_label.setGeometry(QRect(10, 510, 271, 91))
        self.error_message_label = QLabel(Drive)
        self.error_message_label.setObjectName(u"error_message_label")
        self.error_message_label.setGeometry(QRect(20, 470, 151, 41))
        font3 = QFont()
        font3.setPointSize(17)
        self.error_message_label.setFont(font3)

        self.retranslateUi(Drive)

        QMetaObject.connectSlotsByName(Drive)
    # setupUi

    def retranslateUi(self, Drive):
        Drive.setWindowTitle(QCoreApplication.translate("Drive", u"Form", None))
        self.right_speed_label.setText(QCoreApplication.translate("Drive", u"Front_Right", None))
        self.left_speed_label.setText(QCoreApplication.translate("Drive", u"Front_Left", None))
        self.rear_right_speed_label.setText(QCoreApplication.translate("Drive", u"Rear_Right", None))
        self.rear_left_speed_label.setText(QCoreApplication.translate("Drive", u"Rear_Left", None))
        self.wheel_velocity_label.setText(QCoreApplication.translate("Drive", u"Wheel Velocities (Angular)", None))
        self.twist_label.setText(QCoreApplication.translate("Drive", u"Twist", None))
        self.twist_linear_velocity_label.setText(QCoreApplication.translate("Drive", u"Linear", None))
        self.twist_angular_velocity_label.setText(QCoreApplication.translate("Drive", u"Angular", None))
        self.current_robot_location_label.setText(QCoreApplication.translate("Drive", u"Current Robot Location", None))
        self.robot_location_x_label.setText(QCoreApplication.translate("Drive", u"x", None))
        self.robot_location_y_label.setText(QCoreApplication.translate("Drive", u"y", None))
        self.robot_location_z_label.setText(QCoreApplication.translate("Drive", u"z", None))
        self.robot_location_roll_label.setText(QCoreApplication.translate("Drive", u"roll", None))
        self.robot_location_pitch_label.setText(QCoreApplication.translate("Drive", u"pitch", None))
        self.robot_location_yaw_label.setText(QCoreApplication.translate("Drive", u"yaw", None))
        self.error_message_label.setText(QCoreApplication.translate("Drive", u"Error Message", None))
    # retranslateUi

