<?xml version="1.0"?>
<package format="2">
  <name>autonomy</name>
  <version>0.0.1</version>
  <description>Autonomous driving system for the rover</description>

  <maintainer email="your_email@example.com">Your Name</maintainer>
  <license>BSD</license>

  <!-- Build tool dependencies -->
  <buildtool_depend>catkin</buildtool_depend>

  <!-- ROS dependencies -->
  <depend>rospy</depend>
  <depend>roslaunch</depend>
  <depend>std_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>gazebo_ros</depend>
  <depend>sensor_msgs</depend>
  <depend>visualization_msgs</depend>
  <depend>nav_msgs</depend>

  <!-- External Python dependencies (like numpy) -->
  <exec_depend>python-numpy</exec_depend>

  <export>
  </export>
</package>
